### ISSUE TITLE
not a replayable operation

### ISSUE THREAD

**Issue by KasperFranz** [HexagonMC/BungeeCord#106]
> 23:23:22 [SEVERE] [/someRandomIP:56430] <-> InitialHandler - encountered exception
> io.netty.handler.codec.DecoderException: java.lang.UnsupportedOperationException: not a replayable operation
>         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
>         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
>         at protocolsupport.protocol.listeners.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:111)
>         at protocolsupport.protocol.listeners.initial.Minecraft152PingResponseTask.run(Minecraft152PingResponseTask.java:19)
>         at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
>         at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
>         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
>         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
>         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:312)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
>         at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.UnsupportedOperationException: not a replayable operation
>         at protocolsupport.utils.ReplayingDecoderBuffer.reject(ReplayingDecoderBuffer.java:945)
>         at protocolsupport.utils.ReplayingDecoderBuffer.discardSomeReadBytes(ReplayingDecoderBuffer.java:905)
>         at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDecoder.decode(PacketDecoder.java:50)
>         at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDecoder.decode(PacketDecoder.java:17)
>         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
>         ... 17 more

I am not 100% sure why this is happening (seems to be happening mostly for 1.10 players joining (I also use the SpongePI plugin for it to work properly with Sponge but this issue was here before i installed that)

**Comment by KasperFranz** [comment]
and I am sorry for this bad issue, but that is what i have :/ if it is maybe create a default issue layout :)?

**Comment by i9hdkill** [comment]
Bungeeplugins and Hexacordversion? Looks like you have a very old bungeeplugin.

**Comment by KasperFranz** [comment]
Latest hexacordversion and the standard  bungee plugins (cmd_alert, find, list send, server ,reconnect yaml) and EMPBungee (Enjin plugin), PurleBungee IRc and SponghePI

**Comment by i9hdkill** [comment]
`protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core`
What's your spigot version? Maybe try updating Protocolsupport.

**Comment by KasperFranz** [comment]
I got 2 hubs one is 1.7.10 and one 1.10 none of them have  protocolsupport installed

**Comment by i9hdkill** [comment]
Sry I cannot help you if you don't provide useful info.
The error shows clearly that you do have protocolsupport installed.

**Comment by KasperFranz** [comment]
oh jesus wow, It was located in a modules folder I have no idéa why i didn't look there. sorry for that

**Comment by i9hdkill** [comment]
I guess problem sovled?:)

**Comment by KasperFranz** [comment]
doing a restart on the bungee now to check - I feel so stupid :p why does it also check 2 places :p

**Comment by KasperFranz** [comment]
atleast there is no more errors :P

**Comment by KasperFranz** [comment]
but now my hub wont work because of " If you wish to use IP forwarding, please enable it in your BungeeCord config as well!" (the bungee has ip forwarding enabled)

(I have 1 1.7.10 and a 1.10 hub but added under priorities (with the 1.7 first) - do you know what i did wrong?
