### ISSUE TITLE
Allow further customisation of kick text during initial server connection.

### ISSUE THREAD

**Issue by Tyguh** [HexagonMC/BungeeCord#111]
If a user is kicked at present while they are not fully connected to an upstream bridge they will be kicked with a message "Kicked whilst connecting to SERVER: REASON".

While the current code allows us to change "Kicked whilst connect to " (by editing messages.properties) you can not remove the server name from the message. 

Patch: https://github.com/SpigotMC/BungeeCord/pull/1135/commits/6e44a0c92faf4a3a1c4a3556b91284eda67ae224

**Comment by LemADEC** [comment]
Already fixed in ba4625a32e4e546bf34901a44798e13130b876c8 =>close?
