### ISSUE TITLE
Priority bug

### ISSUE THREAD

**Issue by RikoDEV** [HexagonMC/BungeeCord#113]
**BungeeCord version:** This server is running HexaCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:dda70db:118 by md_5

In the latest version the priority is not working properly. I have two servers added to bungeecorda: first version 1.11, the second at 1.7. In older versions of your bungeecord when I joined up with the 1.7 client was connected to the sewer 1.7, but now I'm connected to a server 1.11 and 1.7 server is ignored even though it is 1 priority.

13:06:29 [INFO] [/**.1**.**6.**:3****] <-> InitialHandler has connected
13:06:30 [WARNING] Event PreLoginEvent(cancelled=false, cancelReasonComponents=null, connection=[PolskiRiko2] <-> InitialHandler) took 393,657,995ns to process!

**Comment by i9hdkill** [comment]
Cannot reproduce, likely a problem on your side. Besides that, old ticket.
