### ISSUE TITLE
Cannot connect to SpongeForge servers

### ISSUE THREAD

**Issue by CobaltSparkz** [HexagonMC/BungeeCord#115]
### What Hexacord version are you using? Post the output of /bungee

This server is running HexaCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:5a1da1f:120 by md_5

### Are you using Bungee plugins? If yes, please list all of them + versionnumber

AlwaysOnline Version 5.5
BungeeKick Version 1.2
BungeeMessages Version 1 (No longer working)
MultiCraftFix Version 0.3,
BungeePluginManager Version 1.0,
BungeeYAML Version 1.2.5-SNAPSHOT-36,
ForgeIcon Version 1.0, 
PlayerTabComplete Version 1.1, 
SlashServer Version 3, 
StaffChatBungee 1.2.1, 
SwiftMOTD Version 1.0.4,
Yamler Bungee 2.4.0 Snapshot

### How can we reproduce the error/bug? 

No idea

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.

Outdated Server - This is because my default hub is 1.7.10, and the client I'm using is the 1.10.2 HermitPack (but I'm direct connecting to the Hermit server, but nothing happens)

### In addidtion to that, please explain your issue as detailed as possible.

Apologies if the answer is already somewhere. I've udpated to the latest version of your bungee, my 1.7.10 packs work fine. Trying my 1.10.2 packs doesn't work - connecting to their DNS will either push my onto my 1.7.10 hub, which disconnects me as the Server is out of date, or I simply time out - Looking at the SpongeForge server, I don't see any connection details in the console whatsoever.

If I change my SpongeForge server to an external IP and directly connect, it works fine - It's why I thought Bungee was possibly at fault.

The only information I have about the SpongeForge bungee stuff is from their website - https://docs.spongepowered.org/master/en/server/getting-started/bungeecord.html 

I'm brand new to Sponge, so there could be something I'm missing, but I can't currently see what it is.

If you need logs/testing/further information, please let me know

Thanks

Sparkz

**Comment by i9hdkill** [comment]
Install Spongepls Bungee plugin to fix that.

**Comment by CobaltSparkz** [comment]
Ugh, I hate when I forget simple things! I read about this a while ago, been juggling too many things D: Thanks for the quick reply, much appreciated. Will let you know how I get on

**Comment by i9hdkill** [comment]
Guess it worked?:)

**Comment by CobaltSparkz** [comment]
Hey there! Really sorry about not getting back to you, been super busy and whatnot. It's all working peachy, thank you ever so much for your assistance!
