### ISSUE TITLE
1.5.2-1.6.4 Protocol support?

### ISSUE THREAD

**Issue by Zilacon** [HexagonMC/BungeeCord#117]
Is there any way you guys could add protocol support for 1.5.2 and 1.6.4? I run older modpack servers along with 1.7.10 modpacks and id like to run them all under the same bungee server.

I am using your latest release.
Thank you!

**Comment by i9hdkill** [comment]
No, 1.5 and 1.6 is outdated and shouldn't be supported anymore. 
We will drop 1.7 in a while aswell.

**Comment by Zilacon** [comment]
Could i pay someone to make a supported version?

**Comment by i9hdkill** [comment]
No. Update your modpacks or use other modpacks. Most of them are available for 1.10
