### ISSUE TITLE
clean forge server

### ISSUE THREAD

**Issue by aglarcz** [HexagonMC/BungeeCord#118]
### What Hexacord version are you using? Post the output of /bungee
This server is running HexaCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:652031d:117 by md_5
Protocol support for 1.7.x by Zartec, ghac and I9hdkill

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
spongepls

### How can we reproduce the error/bug? 
try to connect from spigot lobby to 1.7.10 forge server

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
no

### In addidtion to that, please explain your issue as detailed as possible.
Hello guys,
i got bungeecord with spigot lobby connected to cauldron server and it works fine but if i try to connect it to clean forge server 1.7.10 then its not working. Is it possible to somehow connect clean forge server to bungee network?

**Comment by i9hdkill** [comment]
Try without bungee plugins.
Make sure you enabled ip-forwarding on bungeecord.

**Comment by aglarcz** [comment]
Not working, disconnected immediately in bungee Console but nothing at all in forge server console.

**Comment by i9hdkill** [comment]
Ouh yeah, sry ovelrooked that. Clean forge is not working. You will need Cauldron or Sponge.

**Comment by aglarcz** [comment]
So there is no other way how to do it? I need 1.7 because of thaumcraft and other mods but dont wanna cauldron for its bugs and quite low stability.

**Comment by i9hdkill** [comment]
At least I am not aware of any possibilitys to achieve that.

Thaumcraft is available for 1.8.9 Forge. Use that one.

**Comment by MJRLegends** [comment]
Use Kcauldron or thermos which as update to date 1.7.10 cauldron versions/forks

**Comment by i9hdkill** [comment]
Sure, but if a mod supports a higher mc version, there is absolutely no reason to stay on an old version.
Especially when you start a fresh server like aglarcz.

Closing, as this is an issue with vanilla BungeeCord.
