### ISSUE TITLE
Waterfall?

### ISSUE THREAD

**Issue by kwakmantim** [HexagonMC/BungeeCord#12]
Is it possible to merge soms things of Waterfall in this build? (https://github.com/WaterfallMC/Waterfall) its an more optimized version of Bungeecord.

**Comment by i9hdkill** [comment]
Hi,
that's a question we expected. 
We are happy to merge some forge related commits if requested, but we will not merge any "performance" related commits from them.

Some of their commits doesn't make that much sense at all. We try to stay as close as possible to the upstream/original version of BungeeCord.

**Comment by kwakmantim** [comment]
Some do, but thanks for the reply :)

**Comment by ghacproductions** [comment]
If you can tell us some specific ones we can look into it :)

**Comment by kwakmantim** [comment]
Form their list (https://aquifermc.org/threads/welcome-to-waterfall.1/) these look nice:

Throttle joins
- Doesn't interfere with pings
- Fixes spam of 'you are already connected to this server!'
- Since joining takes a lot of processing power, this helps prevent bad people maxing out your CPU with - spam-joins
Tab Complete throttling
- Some bad plugins take a lot of CPU to do tab-complete
- Bad people can take advantage of this and overload your server by spamming tab-complete packets
