### ISSUE TITLE
Bungee crash

### ISSUE THREAD

**Issue by SliderKP** [HexagonMC/BungeeCord#122]
I try to give more than 10gb of RAM to the bungee server and continue to shut down the server with that error

`13:42:02 [SEVERE] [/83.10.228.28:55550] <-> InitialHandler - encountered exception io.netty.handler.codec.DecoderException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 2 byte(s) of direct memory (used: 4660396032, max: 4660396032) at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) at protocolsupport.protocol.listeners.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:111) at protocolsupport.protocol.listeners.initial.Minecraft152PingResponseTask.run(Minecraft152PingResponseTask.java:19) at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:312) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) at java.lang.Thread.run(Thread.java:745) Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 2 byte(s) of direct memory (used: 4660396032, max: 4660396032) at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:624) at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:578) at io.netty.buffer.UnpooledUnsafeNoCleanerDirectByteBuf.allocateDirect(UnpooledUnsafeNoCleanerDirectByteBuf.java:30) at io.netty.buffer.UnpooledUnsafeDirectByteBuf.<init>(UnpooledUnsafeDirectByteBuf.java:68) at io.netty.buffer.UnpooledUnsafeNoCleanerDirectByteBuf.<init>(UnpooledUnsafeNoCleanerDirectByteBuf.java:25) at io.netty.buffer.UnsafeByteBufUtil.newUnsafeDirectByteBuf(UnsafeByteBufUtil.java:624) at io.netty.buffer.UnpooledByteBufAllocator.newDirectBuffer(UnpooledByteBufAllocator.java:65) at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179) at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115) at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:828) at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.FakeSplitter.decode(FakeSplitter.java:16) at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ... 13 more`

**Comment by i9hdkill** [comment]
Don't start Bungee with any java flags.
One of your bungee/spigot plugins is leaking memory. Try without bungee plugins and remove spigot plugins like Featherboard or similiar.

**Comment by SliderKP** [comment]
sorry for my ignorance but any way to detect the problematic server? I have too many servers, maybe... timings?

**Comment by SliderKP** [comment]
Error occurs when it exceeds 60 users ALWAYS, I need to fix it as soon as possible! 

My bungee server has BungeeCord and BungeeProtocolSupport

**Comment by i9hdkill** [comment]
You are not providing ANY information, that would help me to solve your issue and you are not even following my advices.

**Comment by Eufranio** [comment]
It's not the problematic server, It's the problematic plugin. You could post your plugin list.

**Comment by i9hdkill** [comment]
If you need help, provide a bungee plugin list + plugin list of your spigot servers.

**Comment by SliderKP** [comment]
error is in Bungee server not in spigot; plugin list: https://puu.sh/tHxdd/c756f1e410.png

**Comment by i9hdkill** [comment]
Remove protocolsupportBungee. Not needed in any way.

Skinsrestorer is not supported by bungee and WILL cause issues.

**Comment by SliderKP** [comment]
if i remove bungeeprotocolsupport, 1.7 to 1.11 can join?

**Comment by i9hdkill** [comment]
yes.

**Comment by SliderKP** [comment]
ok i will try in some days i tell you if are solved, thanks for your help!
