### ISSUE TITLE
Cannot connect to 1.11.2 server.

### ISSUE THREAD

**Issue by Zilacon** [HexagonMC/BungeeCord#123]
### What Hexacord version are you using? Post the output of /bungee
Latest Release - v123

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
BungeeTabPlus

### How can we reproduce the error/bug? 
Start paper spigot server on hexagon bungee for 1.11.2, try to join.

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
No

### In addidtion to that, please explain your issue as detailed as possible.
When you try to ping or connect at all to a paperspigot server for 1.11.2 on hexagon bungee it does not work. However you can connect/ping just fine on 1.11. I am using the latest version of paperspigot (1044)

**Comment by i9hdkill** [comment]
We are using v123 bungee + paper 1044 on our network. No issues. at all.
Make sure you remove stuff like ViaVersion etc.

**Comment by Zilacon** [comment]
My plugins:
```
[23:33:45] [Server thread/INFO]: Plugins (31): EmptyWorldGenerator, Ram_Monitor, LoginSecurity, GroupManager, WorldBorder, Votifier, ProtocolLib, FastAsyncWorldEdit, StopProxy, mcMMO, Vault, ProtocolSupport, MassiveCore, WorldEdit, Essentials, MCBans, PlotSquared, Multiverse-Core, WorldGuard, Factions, APOCTag, Multiverse-Portals, LimitedCreative, Prism, EssentialsSpawn, GriefPrevention, BungeeTabListPlus, EnjinMinecraftPlugin, UltimateArena, Towny, SilkSpawners
```

Everything worked fine on 1.11 its just upgrading to 1.11.2 is the problem for me.

**Comment by i9hdkill** [comment]
Not a bungee issue, as its working on our side. 
Probably update Protocolsupport.
If its still not working, try without plugins.

**Comment by Zilacon** [comment]
@i9hdkill Its not the plugins and its not ProtocolSupport. I disabled ProtocolSupport, same issue. Removed ALL PLUGINS, same issue.

**Comment by Zilacon** [comment]
With ProtocolSupport i can connect to the server with 1.11 but no matter what i do it will not show up with 1.11.2.

**Comment by i9hdkill** [comment]
Does it work with original BungeeCord?
If not, report your issue there.

You are using forcehosts? Can you connect if you are using ./server <1.11.2serverthatisnotworking>

**Comment by Zilacon** [comment]
I cannot connect to the bungee at all when the hub itself is not accessible. That is the default server. And no i have not tried original bungeecord because i run 1.7.10 servers on this bungee.

**Comment by i9hdkill** [comment]
If the server isn't pingable, check bungee console for errors.

**Comment by Zilacon** [comment]
Just shows InitialHandler and Connection Timeout for my IP.

**Comment by i9hdkill** [comment]
Showing offline with no plugins installed? Weird.
try spigot 1.11.2
If it's working with spigot, check #paper irc channel

**Comment by Zilacon** [comment]
Just switched to Spigot 1.11.2, same result. Server wont ping and showing offline.

**Comment by Zilacon** [comment]
Using Spigot 1.11.2 & PaperSpigot 1.11.2, trying to login with client 1.11.2:
![screenshot_122](https://cloud.githubusercontent.com/assets/3002248/22487240/77100988-e7c1-11e6-81e2-f36200d5c243.png)

Trying to connect with client 1.11:
![screenshot_123](https://cloud.githubusercontent.com/assets/3002248/22487260/8f22cbaa-e7c1-11e6-9593-aa7dd35ba01e.png)

As you can see, it works but not on 1.11.2...

**Comment by i9hdkill** [comment]
Can you pls try for a sec if it works with the 1.8-1.11 BungeeCord?

**Comment by Zilacon** [comment]
Same issue with BungeeCord works on 1.11 but not 1.11.2...

**Comment by i9hdkill** [comment]
Okay, please create a ticket over there a state that your issue happens when using original BungeeCord.

**Comment by i9hdkill** [comment]
I asked you twice to disable all plugins. This should be the first thing you should always do before even creating an issue.

**Comment by Zilacon** [comment]
I didn't think a tablist plugin would be disabling the server from being able to join -_-
Plus i was focusing on the bukkit server for the plugins, because that tablist one was the only thing running on bungee. Now i know that something simple like that can affect the bungee server. Never had a issue like this before.
