### ISSUE TITLE
can't use cart and ship

### ISSUE THREAD

**Issue by RhythmNz** [HexagonMC/BungeeCord#125]
### What Hexacord version are you using? Post the output of /bungee
HexaCord V123 1.7.10

### How can we reproduce the error/bug? 
can't use cart and ship

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
no any message

**Comment by i9hdkill** [comment]
I assume this has been fixed or is no longer an issue. If not, reopen with more info
