### ISSUE TITLE
HexaCord joining error

### ISSUE THREAD

**Issue by Phrancky** [HexagonMC/BungeeCord#127]
### What Hexacord version are you using? Post the output of /bungee
This server is running HexaCord version git:BungeeCord-Bootstrap:1.11-SNAPSHO
T:712982f:127 by md_5

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
I'm not using any BungeeCord plugins at the moment. 

### How can we reproduce the error/bug? 
//

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
https://hastebin.com/ucikebotoy.pas

### In addidtion to that, please explain your issue as detailed as possible.

Whenever a player tries to join they keep getting the error. Everything is setup correctly, this is my config.yml https://hastebin.com/lagutireme.go My lobby has bungeecord=true and online-mode false. The lobby has no plugins. 

Thanks in advance!

**Comment by Zartec** [comment]
You have set your lobby server to restricted here:
```servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: ip:25400
    restricted: true
```
As described by the configuration description this will block all users except those with the right permission:
https://www.spigotmc.org/wiki/bungeecord-configuration-guide/
```
Note: restricted prevents players from joining the server unless they have the bungeecord.server.[servername] permission
```
The priority system of BungeeCord only works if the player is kicked with a massage that contains `outdated`. The case does not matter.

So your problem should be gone if you set `restricted` to `false`.

**Comment by Phrancky** [comment]
Sorry my bad, however, it used to be on false and it didn't work. I've changed it to false again and it still gives me the same error.

**Comment by i9hdkill** [comment]
This message indicates, that BungeeCord can't reach your lobby server for whatever reason.
(wrong port/ip, firewall blocking etc)
You can find more information here:
https://www.spigotmc.org/wiki/bungeecord/
If you need further help, look for help in spigot forums.
