### ISSUE TITLE
Feature request | Add TCP_NODELAY into HexaCord.

### ISSUE THREAD

**Issue by SnakeDaoust1232** [HexagonMC/BungeeCord#132]
Add TCP_NODELAY into HexaCord.

Waterfall has it.

https://github.com/WaterfallMC/Waterfall/blob/master/BungeeCord-Patches/0016-Enable-TCP_NODELAY.patch

**Comment by Zartec** [comment]
So do you have any reasons to add it except "Waterfall has it"

**Comment by SnakeDaoust1232** [comment]
To my understanding, I guess it helps with networking performance.

**Comment by Zartec** [comment]
The `TCP_NODELAY` setting will disable `Nagle's algorithm` which will pack multiple small packets into one tcp packet to reduce overhead.

In detail this means if i send 3 packets containing 1 byte and `TCP_NODELAY` is diabled the socket packs these 3 packts and wraps them into one tcp packet. The resulting size of this packet is `40 bytes tcp header + 3 bytes data`.
If `TCP_NODELAY` is enabled these packets are all sent seperate with the tcp header:
`40 bytes tcp header + 1 byte data + 40 bytes tcp header + 1 byte data + 40 bytes tcp header + 1 byte data`
So there is a overhead of 80 bytes.

Minecraft uses many small sized packets like the look packet.
If there are 100 players on your BungeeCord and all together looking around there can be 20 look packets per player per second. 
These packets will produce an maximum overhead of 79960 bytes.

79,96 kb/s wasted for only one packet that is delivered 2 or 3 milliseconds earlier.

So i don`t see a reason to implement this.

**Comment by SnakeDaoust1232** [comment]
ight, thanks for the explanation.
