### ISSUE TITLE
Problem connecting to bungee with a forge

### ISSUE THREAD

**Issue by unovalegends** [HexagonMC/BungeeCord#135]
### What Hexacord version are you using? Post the output of /bungee

version 1.8
### Are you using Bungee plugins? If yes, please list all of them + versionnumber

1
### How can we reproduce the error/bug? 
Not letting me log into my lobby

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.

https://imgur.com/a/1AWTe
### In addidtion to that, please explain your issue as detailed as possible.
I am trying to connect to my lobby with my  1.10.2 with the forge 1.10.2 - 12.18.3.2185 and before it worked now it keeps giving me errors like that please help me .

**Comment by unovalegends** [comment]
I had it enabled in my bungee file already so I don't understand the issue

**Comment by i9hdkill** [comment]
You need to enable ip-forwarding in bungee and add your sponge server to your spongepls bungee plugin config.
Plus you have to enabe ip-forwarding and bungee in sponge global.conf

**Comment by unovalegends** [comment]
I already did that and still having this issue

**Comment by i9hdkill** [comment]
It definitely works if you follow my steps above.
Post relevant configs so I can double check them.

**Comment by unovalegends** [comment]
Okay one sec

**Comment by unovalegends** [comment]
If I post it here would this be seen in the pulbic ?

**Comment by KasperFranz** [comment]
Yes they will be public

**Comment by unovalegends** [comment]
Isn't that a bit unsafe?

**Comment by KasperFranz** [comment]
he is asking for you config - the configs there might be relevante doesn't contain any personal information or database information.

Which parts of the config do you see as critical not getting out?

**Comment by unovalegends** [comment]
in the config it shows my servers actual ip's

**Comment by KasperFranz** [comment]
And why is it that you don't want to show that?

if your server is play.unovalegends.net then the Ip is  198.24.178.170  - You shouldn't consider a IP as something private, if people wants to find it they will

**Comment by unovalegends** [comment]
Bungee con
http://pastebin.com/p4SncGxf

Gobal Sponge
http://pastebin.com/Tq2s9Caz

Sponge Pl
http://pastebin.com/MBL2qtwd

Lobby2
http://pastebin.com/Y3ZChTwf

**Comment by KasperFranz** [comment]
Can you share you bungee log too and a timestamp where you tried to login with that error

**Comment by unovalegends** [comment]
23.03 12:16:12 [Server] INFO -> UpstreamBridge has disconnected
23.03 12:16:11 [Server] INFO disconnected with: Kicked whilst connecting to lobby2: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!
23.03 12:16:11 [Server] INFO for the target "lobby2".
23.03 12:16:11 [Server] INFO Using the Forge Server Connector for QueenVixen
23.03 12:16:11 [Server] INFO for the target "lobby".
23.03 12:16:11 [Server] INFO Using the Forge Server Connector for QueenVixen
23.03 12:14:17 [Server] INFO Command not found

**Comment by unovalegends** [comment]
This just happen today

**Comment by i9hdkill** [comment]
Remove .* from your spongepls conf. Its a wildcard and may break atuff

**Comment by unovalegends** [comment]
So should I have it only saying -Kanto Region ?

**Comment by unovalegends** [comment]
#####################################
# SpongePls coniguration. YAML ONLY #
#####################################

allowed-servers:
  - ''
  - 'KantoRegion'
  - ''
  - ''

**Comment by unovalegends** [comment]
Like this ?

**Comment by unovalegends** [comment]
Well I try it as you told me and still same message .

**Comment by i9hdkill** [comment]
You are using two bungees? This won't work unless you know what you are doing, but apparently you do not. Otherwise you wouldn't run into problems like this simple forge ip forwarding setup.

**Comment by unovalegends** [comment]
Wait what do you mean I am running two bungee's?

**Comment by unovalegends** [comment]
I am only using 1 bungee

**Comment by i9hdkill** [comment]
You have two different bungee configs.

**Comment by unovalegends** [comment]
No I don't I have a lobby config is that why it causing that ?

**Comment by CheekyOzzie** [comment]
Disable ip forwarding on both like this
https://imgur.com/a/njZxJ

or enable ip forwarding like this
https://imgur.com/a/wceRN

Can't have both at the same time. (In your case you set bungeecord: true on spigot but didn't enable bungeecord ip forwarding.) I think you can figure out which is the bungee config and which is the spigot one.

**Comment by unovalegends** [comment]
I follow your instructions made sure everyone ip forwarding is working but still giving me that issue

**Comment by i9hdkill** [comment]
Definitely works if you follow my advice. Read through configs carefully and visit BungeeCord wiki.
