### ISSUE TITLE
POTION BUG

### ISSUE THREAD

**Issue by ATOM3568** [HexagonMC/BungeeCord#136]
### What Hexacord version are you using? Post the output of /bungee

1.11-SNAPSHOT:8d51253:132 by md_5

### Are you using Bungee plugins? If yes, please list all of them + versionnumber

ABPS
AddvancedBan
AntiBot Attack
AntiMinimap
BPA
Bungee-reconnect
BungeeCordPartyAndFriends
LiteAnnouncer
RangomHub
SkinRestorer
YamlerBungee

### How can we reproduce the error/bug? 

Optimizing the bungee I do not know how this works I do not understand well

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.

Does not give any error it just does not work

### In addidtion to that, please explain your issue as detailed as possible.

I have an error with the pots when I make them or I take them from the inventory I do not give them a bottle of water

And another bug when I put this version instead of the original bungee gave me those problems and gave me a problem with the hits of the server sometimes does not detect them and I would like to see if you can solve that

**Comment by LemADEC** [comment]
No logs, not enough details, very old => close?

**Comment by i9hdkill** [comment]
Reproduce with latest
