### ISSUE TITLE
Cancelling PlayerLoginEvent is handled like ServerKick

### ISSUE THREAD

**Issue by Xayanix** [HexagonMC/BungeeCord#137]
### What Hexacord version are you using? Post the output of /bungee
http://scr.hu/0duk/66yen

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
http://scr.hu/0duk/4xx0a

### How can we reproduce the error/bug? 
Create 1.11.2 server with ProtocolSupport.
Use any plugin which disallows PlayerLoginEvent, if you try to connect to server with version for ex. 1.8 u will be kicked out from proxy.

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
No.

### In addidtion to that, please explain your issue as detailed as possible.
As above.

**Comment by i9hdkill** [comment]
Same behaviour with original BungeeCord?

**Comment by Xayanix** [comment]
I don't know.
