### ISSUE TITLE
IP forwarding problem with forge v2

### ISSUE THREAD

**Issue by fightmaxime** [HexagonMC/BungeeCord#143]
(Old Issue https://github.com/HexagonMC/BungeeCord/issues/139 )
What Hexacord version are you using? Post the output of /bungee

v139

Are you using Bungee plugins? If yes, please list all of them + versionnumber

NO

How can we reproduce the error/bug?

Use Forge 1.8-Forge11.14.1.1334

Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
https://pastebin.com/AEGdQL2m

In addidtion to that, please explain your issue as detailed as possible.
Check the pastebin, I have comback to v132 and that fixed

**Comment by i9hdkill** [comment]
Next time use the old ticket please.
Any errors?

**Comment by fightmaxime** [comment]
Nothing, I want to use the old but is closed xD Sorry
Any errors.

**Comment by timr2000** [comment]
Have the same issue

**Comment by Yann151924** [comment]
I have the same when i try to join a vanilla spigot server

**Comment by i9hdkill** [comment]
For now use the last version, that is tagged as "release".

**Comment by ghacproductions** [comment]
Should be fixed in https://github.com/HexagonMC/BungeeCord/commit/faccbdadb39ecdd561c9fa44a54767d13966efdb. Please test with version v140+.

**Comment by fightmaxime** [comment]
Thank you ! I will test this :)
