### ISSUE TITLE
Add an option to disable saving the player's last server

### ISSUE THREAD

**Issue by Eufranio** [HexagonMC/BungeeCord#147]
I don't want players to join their last server, but I don't want them to be forced in a specific server (force-default-server) too. Could you add an config option to just disable saving the last location of a player? That way, if a player connects trough Forced Hosts he is sent to the forced server, but if he connects trough any other IP he is sent to the lobby/default server, and not his previous one.

**Comment by ghacproductions** [comment]
You could simply set the forced server for your normal ip to your lobby server, I guess.

**Comment by KasperFranz** [comment]
We are doing what you want and we are doing it with these configs:

```
  force_default_server: true
  priorities:
  - hub
```

if they connect to the forced host like beyond then they are sent to that server else they are sent to our hub server

**Comment by Eufranio** [comment]
Is it working with latest HexaCord? I dont see it in the config...

**Comment by Eufranio** [comment]
Oh, I see, sorry.
