### ISSUE TITLE
Bungee Kicks CLient!

### ISSUE THREAD

**Issue by Shoxxo** [HexagonMC/BungeeCord#154]
### What Hexacord version are you using? Post the output of /bungee
 ```quote
This server is running HexaCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:541bef8:148 by md_5

Protocol support for 1.7.x by Zartec, ghac and I9hdkill
```
### Are you using Bungee plugins? If yes, please list all of them + versionnumber
Nope

### How can we reproduce the error/bug? 
Use Forge Client with 1.7.10 and a Spigot Server with Version 1.11.2 with the Plugin ProtocolLib (Allows to connect to the server with lower client version)

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
```quote
03:35:11 [INFO] Listening on /xxx.101.94.230:25565
03:35:17 [INFO] [/xx.201.224.239:48148] <-> InitialHandler has connected
03:35:19 [INFO] [/xx.201.224.239:48013] <-> InitialHandler has connected
03:35:20 [INFO] [ChunkBuster2K7] <-> ServerConnector [lobby] has connected
03:35:20 [INFO] [ChunkBuster2K7] disconnected with: Kicked whilst connecting to lobby: Outdated client! Please use 1.11.2
03:35:20 [INFO] [ChunkBuster2K7] <-> ServerConnector [lobby] has disconnected
03:35:20 [INFO] [ChunkBuster2K7] -> UpstreamBridge has disconnected
```

### In addidtion to that, please explain your issue as detailed as possible.
Detailed informations above ;)

**Comment by Shoxxo** [comment]
After change from ProtocolLib -> ProtocolSupport, it has been worked for me. Seems the Lib was my fail!

![Image of Result](https://image.prntscr.com/image/7ef348d63ec2476d9d16b806db4f8103.png)

**Comment by i9hdkill** [comment]
You are mixing up two things. Protocolsupport allows joining with previous minecraft versions. Protcollib allows packet manipulating. You can run both on your server. ( Make sure you use the latest versions)

**Comment by Shoxxo** [comment]
Sure
