### ISSUE TITLE
Cannot connect to servers on updated HexaCord

### ISSUE THREAD

**Issue by CobaltSparkz** [HexagonMC/BungeeCord#158]
### What Hexacord version are you using? Post the output of /bungee

git:BungeeCord-Bootstrap:1.11-SNAPSHOT:1c2e4bf:129

### Are you using Bungee plugins? If yes, please list all of them + versionnumber

Alwaysonline - 6.1
BungeeKick - 1.2
BungeeMulticraft Playercount Fix- 0.3
BungeePluginManager - 1.0
BungeeYAML - 1.8.8
ForgeIcon - 1.0
PlayerTabComplete - 1.1.1
SlashServer - 3.0
SpongePls - No idea, whatever's on their build server
StaffChatBungee - 1.2.1
SwiftMOTD - 1.0.4
Yamler-Bungee - 2.4.0

### How can we reproduce the error/bug? 
N/A

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
https://pastebin.com/fkZP6wkY

### In addition to that, please explain your issue as detailed as possible.

Was running on version 132 - I don't remember the last update I did, so I tried to update to the latest - V150 (Pastebin of the connection error thrown up - https://pastebin.com/9cFBycbc ) - Nope, no players could connect to any server (modded) with the exception of the spigot hub. Tried V148, nope, same issue. - Pastebin of the error on 148 https://pastebin.com/YKJGX5Eg

Rolled back to the version listed using currently (git:BungeeCord-Bootstrap:1.11-SNAPSHOT:1c2e4bf:129), which I had a backup of from 13.4.17 - Outdated, but it works. The pastebin (https://pastebin.com/fkZP6wkY) relates to the errors in console from the current version I'm using, but at least it works.

Sorry if I missed anything out, please let me know

**Comment by KasperFranz** [comment]
Duplicate of #152 ?

**Comment by raum266** [comment]
Appears to be - If so, 140 WILL work. Out of curiosity, @CobaltSparkz, are you using the Thermal Dynamics & Co mods on that server?

**Comment by CobaltSparkz** [comment]
Apologies that I didn't spot the other thread. Yeah, they are on there - The packs we're using:

Infinity Evolved Normal (1.7.10)
CrundeeCraft
Revenge of the C-Team
RR3 - Mainline

**Comment by raum266** [comment]
So yeah - v140 will let you connect for now, but no 1.12 connectivity .. Unfortunately get one or the other for right now (or remove those mods :P)

 ... A commit has been entered that'll fix it (I've not tested it), but it has not gone into any live build yet. Hopefully soon. 

If you know what you're doing when it comes to git and commits and the like,  you can pull it over yourself - it's linked in the 152 thread.

**Comment by CobaltSparkz** [comment]
Using the most updated version still appears that it doesn't work - Keep using v140 for now?

**Comment by raum266** [comment]
Correct. v140 still works, v159 does not - the fix that went in did not actually fix it, but they now know WHAT the problem is, apparently. There's a little mor einfo in the #152 thread, should you need it.

**Comment by CobaltSparkz** [comment]
Thanks for the heads up, I'll wait and see :) Enjoy your weekend!

**Comment by spannerman79** [comment]
Give https://github.com/HexagonMC/BungeeCord/releases/tag/v243 a try @CobaltSparkz

**Comment by CobaltSparkz** [comment]
Stopped hosting MC around 2 years ago, but thanks @spannerman79 :)
