### ISSUE TITLE
Forcibly Closed By Remote Host *ERROR*

### ISSUE THREAD

**Issue by SAMMIEPLAYS** [HexagonMC/BungeeCord#160]
### What Hexacord version are you using? Post the output of /bungee
1.7 to the latest ver

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
only this one: https://www.spigotmc.org/resources/bungee-spigot-mbanproxyvpn-no-vpn-proxy-countrychecker-universal.32744/

### How can we reproduce the error/bug? 
When you use theplugin even if it's on spigot server with this bungee it has this error: https://gyazo.com/f4dfd61db7a9d382e00b91dbe3877c2c (after you get kicked for using VPN) and i asked the dev, he tried everything but it's the bungee that's causing it.

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
nope but the link above

### In addidtion to that, please explain your issue as detailed as possible.
There is not much to it other than the kick message provided in the image above, if it's 1.8+ bungee it works fine but if it's 1.7 to 1.8+ it just sends that message on any sorta kick message.

**Comment by spannerman79** [comment]
> 1.7 to the latest ver

that is not the output of `/bungee`

**Comment by SAMMIEPLAYS** [comment]
What do you mean, this fork allows 1.7. If i try normal bungee it works fine.
This error only pulls on this ver of bungee.

**Comment by SAMMIEPLAYS** [comment]
I believe it was actually fixed on the latest original bungee.

**Comment by i9hdkill** [comment]
Try our latest version and compare it with original bungee. Make sure you are on both latest.

**Comment by spannerman79** [comment]
@SAMMIEPLAYS I contacted the [dev](https://www.spigotmc.org/members/manercraft.31657/) directly and the dev was kind enough to setup a test instance with the following;

BungeeCord (HexagonMC v140) -> Spigot 1.8.8
Plugin is installed on the BungeeCord instance

I on purpose turned my VPN on and connected to the dev's instance.  It picked up my VPN correctly.
`§6[MBanProxyVPN] : IP: §3195.154.243.5 §6has been detect §4- §6The player was §3Spanner_Man - Method [4, 6, 7, 8] - 41 seconds`

@i9hdkill Please close this issue if there is no futher updates from @SAMMIEPLAYS

**Comment by SAMMIEPLAYS** [comment]
Hello

I will test this version when i get time, i was using the latest one so it might had of had the issue because of that. I will test it when i get time and get back to this thx

**Comment by SAMMIEPLAYS** [comment]
Hello

I'm testing it out now, i'll keep you updated! :)

**Comment by SAMMIEPLAYS** [comment]
Hello

It appears to have the exact same kick message on that version.

**Comment by spannerman79** [comment]
@SAMMIEPLAYS the issue then is your doing.  The dev of MBanProxyVPN already proved to me that this is **not** an issue with MBanProxyVPN nor with HexaCord.

@i9hdkill & @ghacproductions - please close this issue.  Non-reproducible - even with MBanProxyVPN dev assistance as outlined via https://github.com/HexagonMC/BungeeCord/issues/160#issuecomment-309290400

**Comment by SAMMIEPLAYS** [comment]
How is it "not an issue" you're on 1.8 and 1.7 BUNGEE ver isn't showing the message. I can make a video explaining it all if you really don't believe it.

**Comment by SAMMIEPLAYS** [comment]
I've also tried this on spigot version, same effect:


[06:57:51 INFO]: UUID of player Adblock is 81745323-727f-45af-b32b-3b5ae7cc4b92
[06:57:51 INFO]: [MBanProxyVPN] : 38.95.108.232 detect - Player Adblock - Method [2]
[06:57:51 INFO]: [MBanProxyVPN] : IP: 38.95.108.232 has been detect - The player was Adblock - Method [2] - 0 seconds
[06:57:51 INFO]: Adblock[38.95.108.232/38.95.108.232:48539] logged in with entity id 250 at ([Hub]20.289252289286097, 147.0, -2.367291259763871)
[06:57:52 INFO]: CONSOLE issued server command: /ekick Adblock §cIP of Proxy/VPN detects ! \n§6Abusive? Make a post on the forum
[06:57:52 INFO]: Adblock lost connection: §cIP of Proxy/VPN detects !
§6Abusive? Make a post on the forum
[06:57:52 INFO]: §6Player§c Console §6kicked Adblock for §cIP of Proxy/VPN detects !
§6Abusive? Make a post on the forum.
[06:57:52 WARN]: handleDisconnection() called twice


I do run paperspigot but that isn't what the issue is, it keeps showing this message:
https://gyazo.com/f4dfd61db7a9d382e00b91dbe3877c2c

**Comment by spannerman79** [comment]
> How is it "not an issue" you're on 1.8 and 1.7 BUNGEE ver isn't showing the message. I can make a video explaining it all if you really don't believe it.

As I **already** stated before and now **again** via https://github.com/HexagonMC/BungeeCord/issues/160#issuecomment-309290400 - this cannot be reproduced.  This is an issue on **your** end that **you** have created.

Not an issue with HexaCord nor with MBanProxyVPN
