### ISSUE TITLE
1.7 clients kick

### ISSUE THREAD

**Issue by franxyk** [HexagonMC/BungeeCord#161]
### What Hexacord version are you using? Post the output of /bungee
v154

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
SkinRestore last version

### How can we reproduce the error/bug? 
1.7 clients when entering a server 1.7.10

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.

PLAYERNAME lost connection: Internal Exception: net.minecraft.util.io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

**Comment by popcorn9499** [comment]
Are u using forge on that server?

**Comment by gpugeek** [comment]
I'm also having this issue, same Hexacord build.  I've tried with a clean 1.7.10 untouched version too.

**Comment by popcorn9499** [comment]
So u have the same plugins on the bungee cord? Also could u send Ur bungee cord version

**Comment by gpugeek** [comment]
I've found the issue.  It happens when a certain player connects with 1.8.

**Comment by popcorn9499** [comment]
anything special about the player?

**Comment by franxyk** [comment]
The problem is when you use hexagon bungee 1.12 and you have spigot 1.7 servers.
Kick clients join client version 1.7

**Comment by spannerman79** [comment]
> The problem is when you use hexagon bungee 1.12 and you have spigot 1.7 servers.
> Kick clients join client version 1.7

Related to https://github.com/HexagonMC/BungeeCord/issues/152

Seems its more then just forge support of 1.7 that is the issue here.

Downgrade to <=v140 (for now)

**Comment by franxyk** [comment]
From what I see we all have problems with this
No support for 1.7
No way open that wait or if someone has a solution that says: D

**Comment by i9hdkill** [comment]
This issue has been fixed lately
