### ISSUE TITLE
IP issue.

### ISSUE THREAD

**Issue by fanikz** [HexagonMC/BungeeCord#167]
### What Hexacord version are you using? Post the output of /bungee
HexaCord-v156.jar and up

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
BungeePing
ServerlistPlus
Proxypipe-Bungeecord
Liteannouncer
Connectonlimit

### How can we reproduce the error/bug? 
Just use any build starting from HexaCord-v156.jar

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
Nope.

### In addidtion to that, please explain your issue as detailed as possible.
Well basically, all players have wrong IP addresses, everytime they relog they get a new IP. Downgraded to v154 and the issue is solved.

**Comment by i9hdkill** [comment]
Assume that has been fixed on your side. (ip-forwarding)
