### ISSUE TITLE
Not really an issue, but great work everyone at HexagonMC!

### ISSUE THREAD

**Issue by Tom-III** [HexagonMC/BungeeCord#170]
### In addidtion to that, please explain your issue as detailed as possible.
Great work, amazing proxy better than BungeeCord!  Hope the project never dies!

**Comment by ghacproductions** [comment]
Thanks, but please don't forget that the project is based on BungeeCord and the overwhelmingly majority of the sourcecode is identical to the one of BungeeCord. Therefor you should also show your appreciation there ;-)
