### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by SoulWolfX** [HexagonMC/BungeeCord#180]
version
20:10:23 [INFO] This server is running WolfNation version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:e5f4d90:170 by md_5
20:10:23 [INFO] Protocol support for 1.7.x by Zartec, ghac and I9hdkill
>
plugins
skript, server list plus, better nick, advanced ban, bungeeperms, buycraft, bungee cord staff chat,
address limit, stlr fast login, command sync, colored console, and lag monitor

### How can we reproduce the error/bug? 
I don't know

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
https://pastebin.com/bkFH7wiy

### In addition to that, please explain your issue as detailed as possible.
Whenever I log in it kicks me with the message shown in the paste bin...

**Comment by i9hdkill** [comment]
No useful info - I assume it has been fixed on your side. if not, reopen with more info
