### ISSUE TITLE
SkinRestorer..

### ISSUE THREAD

**Issue by jimmy-rich** [HexagonMC/BungeeCord#181]
### What Hexacord version are you using? Post the output of /bungee
Last version

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
Skinrestorer latest on spigotmc

### How can we reproduce the error/bug? 
SkinRestorer not works..

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
Not..

### In addidtion to that, please explain your issue as detailed as possible.
do not see the skin .. before yes no more now ..

**Comment by i9hdkill** [comment]
No version provided + skinrestorer is not supported + no log provided

**Comment by jimmy-rich** [comment]
I can not provide log if there is no error .. logic?

Is there another option?

Another plugin?
Thanks you.
