### ISSUE TITLE
1.7 & 1.8 Problem

### ISSUE THREAD

**Issue by iProGamer** [HexagonMC/BungeeCord#183]
### What Hexacord version are you using? Post the output of /bungee
I am using the latest build #172

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
No, also 0 spigot plugins

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
No error messages at all

### In addidtion to that, please explain your issue as detailed as possible.

I am using the latest build from HexaCord and spigot #1649, everything is working well and no random disconnects or anything, but when a player joins with 1.8+ forge all 1.7 players gets kicked with message: "[Proxy] Lost connection to server" and 1.7 players can't join again because they keep getting kicked with the same message unless the 1.8 forge user disconnects, It's really an annoying problem.
Is this going to be fixed?

**Comment by spannerman79** [comment]
Dupe https://github.com/HexagonMC/BungeeCord/issues/152

**Comment by iProGamer** [comment]
What do you mean?

**Comment by spannerman79** [comment]
Exactly what I commented
[Dupe](http://www.urbandictionary.com/define.php?term=dupe) #152

**Comment by iProGamer** [comment]
@ghacproductions @i9hdkill @Zartec

**Comment by NotixMLG** [comment]
I have same problem and download this if want work https://yivesmirror.com/grab/hexacord/HexaCord-v139.jar

**Comment by iProGamer** [comment]
I already solved it, thanks

**Comment by NotixMLG** [comment]
How ?

**Comment by iProGamer** [comment]
You find the solution here: https://github.com/HexagonMC/BungeeCord/issues/152

**Comment by i9hdkill** [comment]
This issue was fixed lately
