### ISSUE TITLE
Does HexaCord require ProtocolSupport?

### ISSUE THREAD

**Issue by Zaid-Ali** [HexagonMC/BungeeCord#184]
### What Hexacord version are you using? Post the output of /bungee
29.09 17:08:18 [Server] INFO This server is running HexaCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:9d5ade5:172 by md_5
29.09 17:08:18 [Server] INFO Protocol support for 1.7.x by Zartec, ghac and I9hdkill

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
MOTDCountdown, SERVERLISTPLUS

### In addition to that, please explain your issue as detailed as possible.
I'm confused as to why I am receiving the "Outdated Client! Please use 1.8.8" message when trying to connect to my 1.8 server on 1.7.10 with HexaCord installed (which I thought had protocol support).

Bungee: Hexa Installed and set to forward to Factions.
Factions Server: PaperSpigot 1.8.8

I'm attempting to allow 1.7 players join a 1.8.8 server.

**Comment by i9hdkill** [comment]
Hi, you still need protocolsoftware on every spigot server. Like Protocolsupport and/or ViaVersion

**Comment by Zaid-Ali** [comment]
Does anyone know which version of Protocol Support works, cause when I install the latest one and put it on my spigot server it - when I start the server plugins load and then automatically disable.

**Comment by i9hdkill** [comment]
Get spigot 1.12.2 + latest PS Dev Build to support 1.5-1.12.2 or use spigot 1.8.8 + ViaVersion to support 1.8.8 - 1.12.2. There a no other (good) working solutions. But thats not a bungee issue. Ask in spigot forums or Protocolsupport Discord.
