### ISSUE TITLE
InitialHandler - read timed out

### ISSUE THREAD

**Issue by minecraft7net** [HexagonMC/BungeeCord#192]
### What Hexacord version are you using? Post the output of /bungee
version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:5e67309:183

### How can we reproduce the error/bug? 
i need help how to debug it - any options for more detailed logs?

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
don't know

bungeecord log:
12:45:05 [WARNING] [ip-cut] <-> InitialHandler - read timed out
12:45:40 [WARNING] [ip-cut] <-> InitialHandler - read timed out
12:45:56 [WARNING] [ip-cut] <-> InitialHandler - read timed out
13:00:14 [WARNING] [ip-cut] <-> InitialHandler - read timed out
13:04:19 [WARNING] [ip-cut] <-> InitialHandler - read timed out
13:07:53 [WARNING] [ip-cut] <-> InitialHandler - read timed out
13:11:53 [WARNING] [ip-cut] <-> InitialHandler - read timed out
13:24:15 [WARNING] [ip-cut] <-> InitialHandler - read timed out
13:29:07 [WARNING] [ip-cut] <-> InitialHandler - read timed out
13:39:35 [WARNING] [ip-cut] <-> InitialHandler - read timed out
13:48:42 [WARNING] [ip-cut] <-> InitialHandler - read timed out
13:51:36 [WARNING] [ip-cut] <-> InitialHandler - read timed out
13:56:25 [WARNING] [ip-cut] <-> InitialHandler - read timed out
13:57:17 [WARNING] [ip-cut] <-> InitialHandler - read timed out
14:01:50 [WARNING] [ip-cut] <-> InitialHandler - read timed out
14:06:15 [WARNING] [ip-cut] <-> InitialHandler - read timed out
14:06:18 [WARNING] [ip-cut] <-> InitialHandler - read timed out

### In addidtion to that, please explain your issue as detailed as possible.
probably clients disconnects or problems with connections to server (?)

**Comment by popcorn9499** [comment]
ok so what I would recomend is things like can a client connect at all. If so then what version of the minecraft client are you trying to use. modded, unmodded. Then look at the minecraft server it is trying to go to. any logs in its console? Would you be able to tell me that information?

**Comment by i9hdkill** [comment]
Likely not an issue with Bungee. If you still got problems, provide more useful info
