### ISSUE TITLE
No /server?

### ISSUE THREAD

**Issue by LoXR** [HexagonMC/BungeeCord#195]
### What Hexacord version are you using? Post the output of /bungee
Latest Hexacord [#26](https://ci.lucko.me/job/HexaCord/26/)

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
No

### How can we reproduce the error/bug? 
Simple /server

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
Just Unknown Command

### In addidtion to that, please explain your issue as detailed as possible.
Normal Bungeecord has the /server option, but why doesnt Hexacord have it?

**Comment by spannerman79** [comment]
Before blaming Hexacord check to make sure that you/the player has the permission node `bungeecord.command.server`

Luckperms as well as others have a way to check this - use the needed command to verify.

**Comment by LoXR** [comment]
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list

**Comment by LoXR** [comment]
Alright note to self, down the official build not the jenkins build.... :')
