### ISSUE TITLE
Spam log

### ISSUE THREAD

**Issue by manercraft** [HexagonMC/BungeeCord#20]
Hello,
I use your version of BungeeCord but my logs are verry spam
(~3330 lines/s)
With this error http://pastebin.com/j6TG1NRq

**Comment by i9hdkill** [comment]
Might be related to the latest bungee commit.
Can you update to our latest build?

**Comment by manercraft** [comment]
I use v43
This is a person who sends me "special" bot who is trying to crash my server.
Standard Bungeecord with this crash.
With your bungeecord, no crash but large errors in the logs

**Comment by i9hdkill** [comment]
The latest original BungeeCord build crashes in this situation? That would be quite weird. The other way around would make more sense. Anyway, we need to wait for @Zartec

**Comment by ghacproductions** [comment]
The message itself should come from https://github.com/HexagonMC/BungeeCord/commit/1dda27e19bf8bf61121ed5cad92e40fd8baa924f#diff-cde8e0bfd70cda93f1098dd45704f431L51, as this prevents the server from crashing, it's 'just' spamming in the console. I'm not sure, why this is not happening on the original BungeeCord, unfortunately I don't have this client to do some tests.

**Comment by manercraft** [comment]
Yes the original version of BungeeCord crash after ~10s in 1.7 but not in 1.8
But I need 1.7 version
Now, my server is start since four hours and isn't crash.

Yes this spam the console but isn't possible to read log with 3330 lines of errors/seconds

**Comment by i9hdkill** [comment]
Ah yea, the original 1.7 bungeecord will crash. I thought you were talking about the 1.9 one.
We are trying to reproduce this on the original Bungeecord 1.9, if this messages are coming up aswell.

**Comment by manercraft** [comment]
Sorry I forgot to mention it
I think the problem is fixed in this build:
http://ci.md-5.net/job/BungeeCord/1138/

**Comment by i9hdkill** [comment]
This commit adds a limit (128)
https://github.com/SpigotMC/BungeeCord/blob/6b4e2851869989cb15126c229c151465cc27f212/protocol/src/main/java/net/md_5/bungee/protocol/packet/EncryptionResponse.java#L23
The error is telling, that someone tries to send more then 128.

**Comment by manercraft** [comment]
And would it be possible to disable the log of this error via a configuration?

**Comment by i9hdkill** [comment]
We will silence the error, have a look at our releases today.
But at first we need to repoduce, if this error appears on the original 1.9 Bungeecord too.

**Comment by manercraft** [comment]
Ok thank !!

**Comment by ghacproductions** [comment]
Do you have the client that can produce these lines? Or can you maybe ask that player of your server?

**Comment by manercraft** [comment]
No sorry i don't have this client.
And I can't ask to this player, he is hostile. He wants to crash my server ^^

**Comment by Zartec** [comment]
Pull request is out SpigotMC/BungeeCord#1815

This will limit log output to the error message.

**Comment by manercraft** [comment]
Hello,
Do you have any news ?

**Comment by Zartec** [comment]
Noe sry, the pull request is still open.
