### ISSUE TITLE
Players with 1.7 are getting disconnected when someone join to the server

### ISSUE THREAD

**Issue by MiMic10110** [HexagonMC/BungeeCord#203]
Players with 1.7 are getting disconnected when someone will join to the server with information "[Proxy] Lost connection to the server".
I am using newest bungeecord from HexagonMC fork (allows 1.7), newest spigot and newest protocolsupport with protocolsupportlegacysupport.
Else plugins installed: WorldEdit, FastAsyncWorldEdit, WorldGuard, EssentialsX.
My java is 1.8.

Here is what is in spigot server logs:
[19:28:28] [Server thread/INFO]: Player336 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

And this is in bungeecord log:
19:28:28 [INFO] [Player336] disconnected with: §f[Proxy] Lost connection to server.

This problem happens ONLY with version 1.7. 1.8+ does not have this problem.

Thanks for any help.
https://github.com/ProtocolSupport/ProtocolSupport/issues/812

**Comment by popcorn9499** [comment]
So  basically is the 1.7 client and server modded or not?

**Comment by Encode17** [comment]
Clear 1.7 without any modifications, server too - only installed listed plugins, but I do not think that they are referenced to this.

**Comment by Encode17** [comment]
Found problem cause:
player.setPlayerListName(name);

Using this method on someone will cause this disconnect.
I was testing it on PlayerJoinEvent. Everytime 1.7 players are getting kicked.
Please, fix it.

**Comment by i9hdkill** [comment]
Fixed in PS
