### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by PiiSaba** [HexagonMC/BungeeCord#205]
### What Hexacord version are you using? Post the output of /bungee
SNAPSHOT:b5f17e7:190 
Latest Hexacord

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
Yes I do.
ABPS(latest), AntiBotDeluxe(Mysql, latest), BungeeHub(latest), BungeePerms(latest), BungeeWhiteList(latest), SuperAntiWDL(latest)

### How can we reproduce the error/bug? 
I am using CentOS on my server. when I am using Ubuntu BungeeCord was not crashed.
I do not know how to fix the crash. I gave BungeeCord 5gb memories but It crashed..

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
https://pastebin.com/SHaQUSa8

### In addidtion to that, please explain your issue as detailed as possible.
I pulled out the plug-n as much as possible and gave a lot of memory and tried it, but it crashed.
When using Ubuntu it never crashed, it has crashed after switching to CentOS.
I tried to find a solution on the Internet, but I could not find it.

**Comment by i9hdkill** [comment]
Not an issue with BungeeCord. One of your plugins is leaking memory.
