### ISSUE TITLE
Unknown meta type 15

### ISSUE THREAD

**Issue by JoeSGT** [HexagonMC/BungeeCord#207]
### What Hexacord version are you using? Post the output of /bungee
v196

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
nothing no plugins cause i did testing and confirm the bug

### How can we reproduce the error/bug? 
Make a Sponge server and connect it with Bungeecord then
make sure you install the immersive engineering mod then get an item called Chemical Thrower put fluid in it you could use another mod called thermal  expansions and get an fluid transposer an quick easy way to transfer fluid in Chemical Thrower then once the fluid in it any type of fluid then right click the item and boom you will get kicked by bungeecord this does not happen without bungeecord installed and the player ingame cannot join back until they are teleport while they are offline away from the area they right click the Chemical Thrower if they go back the area they right click it with they will get kick  again.

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
https://pastebin.com/PuXpkU2x

**Comment by LemADEC** [comment]
https://github.com/WaterfallMC/Waterfall/issues/216
https://github.com/HellFirePvP/AstralSorcery/issues/547
Forge (Vanilla?) allows to create your own dataserializers so there's no 'invalid protocol' here per say, it's just next to impossible to handle for a proxy 'as is'.

**Comment by JoeSGT** [comment]
I see I'll just grab a copy of the source files and remove the meta types for better mods support thanks you @LemADEC

**Comment by LemADEC** [comment]
This issue has nothing to do with forced hosts @spannerman79

**Comment by i9hdkill** [comment]
See Waterfall issue. There might be even a branch/config option that fixes that by rewriting the whole entity rewriting system, which has also downsides

**Comment by Sir-Will** [comment]
Does or will this fork not provide a fix for this?

**Comment by i9hdkill** [comment]
This fork does not and won‘t provide a fix for this
