### ISSUE TITLE
IndexOutOfBoundsException on v43

### ISSUE THREAD

**Issue by TiTo-418** [HexagonMC/BungeeCord#21]
Logs: http://pastebin.com/tZxBpBXn
Let me explain what I'm trying to do:
I have your custom bungee (1.7,1.8,1.9) with ProtocolSupportBungee
I have a lobby in 1.9 which allows 1.7,1.8 and 1.9 clients (using ProtocolSupport)
I have another server 1.7 that allow 1.8 clients.
When I try to switch from the Lobby to the 1.7 server it gives me that error in chat and the error posted above in the bungee conosole
![2016-04-03_05 30 36](https://cloud.githubusercontent.com/assets/11008016/14231531/38277074-f95d-11e5-9217-ddd6333e19b5.png)

Note: I can join normally with the regular ip without using bungee

**Comment by i9hdkill** [comment]
Our BungeeCord and ProtocolSupportBungee are pretty much doing the same thing. Use either our Bungee or Protocolsupportbungee.

**Comment by TiTo-418** [comment]
I tried with yours and it's still an issue

**Comment by i9hdkill** [comment]
Which bungee plugins are you using? Seema like you have an outdated one

**Comment by Tim-NL** [comment]
@i9hdkill ProtocolSupportBungee doesn't do the same thing, it adds support for 1.5 / 1.6 not 1.7. (No sure why tho..)

**Comment by i9hdkill** [comment]
I know, but there is absolutely no reason using our bungee when you wanna have 1.5 etc support. Then you should use the original bungee with Protocolsupportbungee Using both can have unwanted side effects.

**Comment by TiTo-418** [comment]
@i9hdkill I tried removing all the plugins, and it still no working

**Comment by iFluzzer** [comment]
TiTo-418 Tito did u solve it?

**Comment by TiTo-418** [comment]
@iFluzzer Nope

**Comment by ghacproductions** [comment]
@TiTo-418 Are there any messages in the spigot-server-log?

**Comment by TiTo-418** [comment]
@ghacproductions Yes:

```
[09:17:04 INFO]: TiTo_418[/127.0.0.1:65266] logged in with entity id 1 at ([world]9.143514041118014, 28.5, 14.300000011920929)
[09:17:10 INFO]: UUID of player TiTo_418 is 03b93a67-db69-3ddf-aecf-cc04b8a26922
[09:17:10 INFO]: TiTo_418 lost connection: You logged in from another location
[09:17:10 INFO]: TiTo_418[/127.0.0.1:65268] logged in with entity id 2 at ([world]9.143514041118014, 28.5, 14.300000011920929)
[09:17:10 WARN]: handleDisconnection() called twice
[09:18:41 INFO]: UUID of player TiTo_418 is 03b93a67-db69-3ddf-aecf-cc04b8a26922
[09:18:41 INFO]: TiTo_418 lost connection: You logged in from another location
[09:18:41 INFO]: TiTo_418[/127.0.0.1:65293] logged in with entity id 3 at ([world]6.583761240570603, 28.0, 10.187073546804402)
[09:18:41 WARN]: handleDisconnection() called twice
```

**Comment by ghacproductions** [comment]
@TiTo-418 Just one question, is your server in online mode? If so, is bungeecord set to true in the spigot.yml file?

**Comment by TiTo-418** [comment]
@ghacproductions All the servers are in offline mode with bungeecord set to true

**Comment by ghacproductions** [comment]
@TiTo-418 And your bungeecord is in offline or online mode?

**Comment by TiTo-418** [comment]
@ghacproductions Online

**Comment by ghacproductions** [comment]
@TiTo-418 Is the ip-forward setting in the BungeeCord config.yml set to true?

**Comment by TiTo-418** [comment]
@ghacproductions Yes

**Comment by ghacproductions** [comment]
Your uuid 03b93a67-db69-3ddf-aecf-cc04b8a26922 is offline, it should be online!

**Comment by TiTo-418** [comment]
@ghacproductions So...?

**Comment by ghacproductions** [comment]
I'm not sure, are you using IRC so we could try this fix this issue together?

**Comment by ghacproductions** [comment]
Just to keep it here, it was caused by an unsupported sportsbukkit version.
