### ISSUE TITLE
Use patch files instead of having the whole source

### ISSUE THREAD

**Issue by DoNotSpamPls** [HexagonMC/BungeeCord#211]
This will make the modifications made by Hexacord a lot more maintainable (just look at Paper/Waterfall).

**Comment by i9hdkill** [comment]
Hi,
yes you could be right. But keep in mind we simply merge from upstream, no extra patches like Paper/Waterfall. Additionally our devs that maintained this fork quit developing for mc. They merge changes occasionally when I request it. They do not have time to setup patches initially, left alone applying further patches.

**Comment by DoNotSpamPls** [comment]
Well, you have done some modifications to the code to allow 1.7, so that could be converted to patch files in the future. Nobody is asking for new features. Also, you could have upstream as a submodule, it's way easier to update that

**Comment by kjl13** [comment]
Can you please merge from upstream? @i9hdkill

**Comment by ghacproductions** [comment]
As @i9hdkill already mentioned, @Zartec and me, who patched HexaCord the most, don't activly develop for MC anymore. Therefor, at least from me, there won't be any "breaking changes" to HexaCord. If you provide the patches, we can look at them and maybe change the buildscript to use them, but at the moment, I don't have interest and time in doing this.

You can reopen the issue if you created the patches.

**Comment by DoNotSpamPls** [comment]
I made a repository (https://github.com/DoNotSpamPls/Hexacord) which includes a completely revamped process with patches, inspired by Waterfall's. I'd love it if you can check it out and decide if you want to add it.
