### ISSUE TITLE
1.13 support from 1.7.X

### ISSUE THREAD

**Issue by UnNamedAndre** [HexagonMC/BungeeCord#213]
I’m using the latest version of hexacord.. can you add 1.13 support? i’d like from 1.7.X to 1.13.X

**Comment by kjl13** [comment]
All they have to do is merge with upstream.

**Comment by i9hdkill** [comment]
It's merged. But sponge/Forge support with ip forwarding enbaled is broken atm. Use with care. For now, a 1.12 build + ViaVersion is the better choice

**Comment by ghacproductions** [comment]
Please try version 204 and see if this fixes your problems.

**Comment by i9hdkill** [comment]
No response - I assume it's working
