### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by DrexPlayz** [HexagonMC/BungeeCord#215]
### What Hexacord version are you using? Post the output of /bungee
Lastest v204

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
SlashServer - Version 3

### How can we reproduce the error/bug? 
When a player connects to another server from the Lobby (some other players do not happen to them > 1.8 players)

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
Bungee: https://pastebin.com/aG8kG6zN
Client: https://pastebin.com/2LSDF7wG

### In addidtion to that, please explain your issue as detailed as possible.
This happens to some players, there are times when it does not happen at all, it's a bit strange since the whole Bungee configuration is correctly, then connect the player to the server and then return it to the lobby, in this case it came out to me using the CheatBreaker..

**Comment by i9hdkill** [comment]
Thanks for the report, we think we know where this is coming from

**Comment by DrexPlayz** [comment]
you're welcome ;)

**Comment by i9hdkill** [comment]
@DrexPlayz Hey, could you please test this build?
https://www.dropbox.com/s/3xmhhzica8vg9j3/BungeeCord_205_Test.jar?dl=0

**Comment by DrexPlayz** [comment]
I will test it ;)

**Comment by DrexPlayz** [comment]
@i9hdkill I just did the same procedure and the same thing keeps happening to me, the bungee console gives this error: https://pastebin.com/mNJpergk

**Comment by ghacproductions** [comment]
@DrexPlayz Could you please test this build?
https://owncloud.ghac.de/index.php/s/od7PTgSpnTJKtzj

**Comment by DrexPlayz** [comment]
@ghacproductions of course

**Comment by DrexPlayz** [comment]
@ghacproductions It works correctly now 👍

**Comment by ghacproductions** [comment]
@DrexPlayz Alright, you can use the relases v205+ from the [releases tab](https://github.com/HexagonMC/BungeeCord/releases) now, which also include the fix.
