### ISSUE TITLE
Could you allow Bungee - Bungee Connetction

### ISSUE THREAD

**Issue by root1599** [HexagonMC/BungeeCord#226]
Could you enable bungee - bungee i know it sounds pointless but its not for my use it was disabled in this commit https://github.com/SpigotMC/BungeeCord/commit/504d3c0529e2014d5a1c469206db3bfd440829a7#diff-cde8e0bfd70cda93f1098dd45704f431

**Comment by i9hdkill** [comment]
No - but you can fork this project and change it yourself
