### ISSUE TITLE
Using this with a big network

### ISSUE THREAD

**Issue by iFluzzer** [HexagonMC/BungeeCord#23]
Hello, sry for posting this here, but i didnt find anther way to cntact you, well my question is, i have a network with 500-800 Players with +80 Servers i want to know if ill have issues using this bungee

**Comment by Zartec** [comment]
There should be no problem running this BungeeCord on a large network.
This Version is running and tested with 220 players online on our servers (~15 servers active played).
The performance should be near to the original server (additional protocol version checks and packet translations for 1.7.x)

**Comment by iFluzzer** [comment]
Anyone here? Need help kinda urgently

**Comment by ghacproductions** [comment]
Hey, do you use IRC?

**Comment by iFluzzer** [comment]
Yes

**Comment by ghacproductions** [comment]
@iFluzzer Then please join #hexagonmc on irc.spi.gt
