### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xCraftRayX** [HexagonMC/BungeeCord#231]
### What Hexacord version are you using? Post the output of /bungee
This server is running MineS.pl version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222 by md_5
Protocol support for 1.7.x by Zartec, ghac and I9hdkill

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
UltimateReporter 1.9 Java 8
BungeeAdminTools-1.4.3-basics
BungeeChatFilter-1.8
BungeeRcon-2.1
ChangeSkinBungee
cmdispatcher-3.0.3
GlobalBroadcastBungee_v1.0.0
HubMagic-0.2.6
kotlin4mc-2.0.7
LuckPerms-Bungee-4.3.9
ServerListPlus-3.4.8-Universal
SlashServer
sockets4mc-4.0.9
Yamler-Bungee-2.4.0-SNAPSHOT

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
https://pastebin.com/k9U23qpT

### In addidtion to that, please explain your issue as detailed as possible.
I don't know why I get this error.

**Comment by BadBoyHalo** [comment]
Huh

**Comment by i9hdkill** [comment]
Broken NBT somehwere on your spigot server or something similiar
