### ISSUE TITLE
1.7.10 player got kicked

### ISSUE THREAD

**Issue by KiloMinx** [HexagonMC/BungeeCord#241]
### What Hexacord version are you using? Post the output of /bungee
11:35:54 [INFO] This server is running Pyraminx version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222 by md_5
>
11:35:54 [INFO] Protocol support for 1.7.x by Zartec, ghac and I9hdkill

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
no

### How can we reproduce the error/bug? 
Use a "1.8.9-forge1.8.9-11.15.1.2318-1.8.9" to /server to a server that is running "CraftBukkit git-Spigot-1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)" while a vanilla 1.7.10 is already in the server that the 1.8.9 client is going to, the 1.7.10 client will got kick with the following message: "[Proxy] Lost connection to server."

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
https://pastebin.com/4UFfZd3B

### In addidtion to that, please explain your issue as detailed as possible.
When the is a 1.8 or above client with forge installed in the spigot server, any player with 1.7 client will got kicked

**Comment by cuervito** [comment]
hello the same thing happens to me. can fix that flaw, if a user plays with forge 1.8. and another one with 1.7.10 enters it kicks it with proxy error. the only version that walks me of hexacord is the 198

**Comment by spannerman79** [comment]
https://github.com/HexagonMC/BungeeCord/issues/237#issuecomment-456199924

**Comment by spannerman79** [comment]
Give https://github.com/HexagonMC/BungeeCord/releases/tag/v243 a try
