### ISSUE TITLE
Use patch files instead of having the whole source [part 2]

### ISSUE THREAD

**Issue by DoNotSpamPls** [HexagonMC/BungeeCord#242]
I made a repository (https://github.com/DoNotSpamPls/Hexacord) which includes a completely revamped process with patches, inspired by Waterfall's. I'd love it if you can check it out and decide if you want to add it or not.

**Comment by cuervito** [comment]
> I made a repository (https://github.com/DoNotSpamPls/Hexacord) which includes a completely revamped process with patches, inspired by Waterfall's. I'd love it if you can check it out and decide if you want to add it or not.

Hi . could you help me, and give me a hexacoord latest version but that works with the 1.7.10 and 1.8 forge and does not disconnect my users by proxy thanks
example
https://github.com/HexagonMC/BungeeCord/issues/241

**Comment by cuervito** [comment]
![proxy lost coneection](https://user-images.githubusercontent.com/38864132/51489515-4eb84380-1d87-11e9-86e0-a82903cc8b4d.png)

**Comment by DoNotSpamPls** [comment]
why are you responding in this issue? i can't fix it as I'm not the maintainer of hexacord. go try waterfall or something if hexacord doesn't work for you

**Comment by cuervito** [comment]
@DoNotSpamPls  hello, sorry, I thought you knew how to fix this problem .. I already tested with travertine and also that proxy failure .. I will continue using hexacord version 1.98 which is the only one that works well

**Comment by DoNotSpamPls** [comment]
@i9hdkill @sleiss could you please have a look at this? thanks!
