### ISSUE TITLE
No velocity bug

### ISSUE THREAD

**Issue by DanielAlves123** [HexagonMC/BungeeCord#243]
Everyone has no velocity and no knockback, on newest bungeecord and viaversion.

**Comment by DadeyGF** [comment]
same

**Comment by L4BORG** [comment]
Same, downgrading Hexacord fixed the issue.

**Comment by i9hdkill** [comment]
Report this to ViaVersion

**Comment by i9hdkill** [comment]
Fixed, thanks to @MylesIsCool
