### ISSUE TITLE
Suggestion: Update MOTD from config.yml on /greload

### ISSUE THREAD

**Issue by d4julian** [HexagonMC/BungeeCord#246]
### What Hexacord version are you using? Post the output of /bungee
1.13-SNAPSHOT:4d50148:225

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
N/A

### How can we reproduce the error/bug? 
Try /greload in bungeecord console, wait to MOTD to update, but it doesn't...

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
Bungee

### In addidtion to that, please explain your issue as detailed as possible.
Allow bungee to reload the MOTD in config.yml upon /greload

**Comment by spannerman79** [comment]
There are **many** bungeecord plugins that do this job already. http://bfy.tw/Mmin
