### ISSUE TITLE
1.7 with EntityStatus Packet

### ISSUE THREAD

**Issue by ThatKawaiiAllen** [HexagonMC/BungeeCord#249]
### What Hexacord version are you using? Post the output of /bungee
Latest

### Are you using Bungee plugins? If yes, please list all of them + version number
No

### How can we reproduce the error/bug? 
Join with 1.7 clients, and send entity status packet

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
Yes, https://i.imgur.com/f2ojh3Z.png

**Comment by spannerman79** [comment]
Direct connecting to a 1.7 server or via hub server -> 1.7 server?
Need more details in order to replicate.

**Comment by ThatKawaiiAllen** [comment]
1.7.10 PaperSpigot, so yes it is a 1.7 server

**Comment by ThatKawaiiAllen** [comment]
![1`D%FZT4NGR}WJ3~B5Z%UXJ](https://user-images.githubusercontent.com/20222292/56548114-0fd78c80-6534-11e9-8eef-a0cab78b1d90.png)

I did a little bit of research and added these two lines, I'm going to see if it works

**Comment by ThatKawaiiAllen** [comment]
Nevermind not really, the server throws a NoClassFound error when I'm doing this.

**Comment by ThatKawaiiAllen** [comment]
Solved by myself, will create a PR as soon as possible.
