### ISSUE TITLE
thaumic.tinkerer Issue?

### ISSUE THREAD

**Issue by KaneHart** [HexagonMC/BungeeCord#25]
I can't seem to connect even to the lobby world no server errors or bungee just the client:
http://pastebin.com/NQNBgxxB

Not sure if this is something you can fix or not :)

**Comment by i9hdkill** [comment]
Lobby world for a modded network should be a clean spigot 1.7.10 server.
What exactly are you trying to do?
Lobby spigot version?

**Comment by KaneHart** [comment]
It's 1.9 but using another method for it. It works with most modded clients. After removing the mod it seems like another mod is breaking it:
http://pastebin.com/tFCiLfG4

I guess that is it for modded minecraft and bungee. Going to close this I'm sure nothing in your area.
