### ISSUE TITLE
Latest version is incompatible with 1.7.10 servers

### ISSUE THREAD

**Issue by N0tMyFaultOG** [HexagonMC/BungeeCord#252]
### What Hexacord version are you using? Post the output of /bungee
This server is running HexaCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:4d50148:225 by md_5
Protocol support for 1.7.x by Zartec, ghac and I9hdkill

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
https://pastebin.com/Bm2SnZDK

### How can we reproduce the error/bug? 
Use any build newer then v225, they seem no longer to work with with 1.7.10

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
https://pastebin.com/9tLULT0r

### In addidtion to that, please explain your issue as detailed as possible.
There is not much I can add to that, using any newer build than v225 seems to disconnect the player instantly with the error given above,

**Comment by spannerman79** [comment]
```
"name": "ProxyChannels",
                "version": "2.0.3-SNAPSHOT",
```
https://www.spigotmc.org/resources/proxychannels-redisbungee-support.34255/

> This code has ONLY been tested against **MC 1.12** running the latest BungeeCord. It is built against **BungeeCord 1.8**, so it should work fine for most servers. If it does not, please tell me and I will fix it for your needs. Please do not leave a bad review before attempting to have me fix the code for your needs. That is what a beta is about, after all. Leaving an unwarranted bad review will discourage me from continuing this project for free.

`java.lang.IllegalArgumentException: Cannot get ID for packet class`
Prob a plugin on the Bungee instance - check them first.

**Comment by i9hdkill** [comment]
Check that first yes, but there is a PR open that might aim that issue

**Comment by N0tMyFaultOG** [comment]
> Check that first yes, but there is a PR open that might aim that issue

Already did earlier, but disabling doesn't fix it

**Comment by i9hdkill** [comment]
Please test latest build

**Comment by N0tMyFaultOG** [comment]
I'll give it a try later this day 👍

**Comment by N0tMyFaultOG** [comment]
The EntityStatus part seems to be fixed but connection isn't possible still https://pastebin.com/PWDmXKMZ

**Comment by Sir-Will** [comment]
This https://github.com/HexagonMC/BungeeCord/pull/157 seems to be no longer there in the latest versions.
Also IP forwarding seems to be broken for 1.7. (It's enabled in the config but the server shows localhost)

**Comment by i9hdkill** [comment]
Oh well, that‘s really a mess. Probably won‘t make to look into it the next time. If anyone actually uses 1.7.10 support, feel free to pr the change. I would appreciate it

**Comment by dogboy21** [comment]
I've created a PR(#261) which readds my changes from #157 :)

**Comment by spannerman79** [comment]
@N0tMyFaultOG & @Sir-Will give https://github.com/HexagonMC/BungeeCord/releases/tag/v243 a try

**Comment by N0tMyFaultOG** [comment]
That seemed to fix it, thx a lot @dogboy21
