### ISSUE TITLE
BungeeCord log-DIR

### ISSUE THREAD

**Issue by xXSchrandXx** [HexagonMC/BungeeCord#255]
### What Should Be Added
BungeeCord logs are quite massive after some time. Could you move them to a log folder, give times, and compress them.

### Why It Should be Added
Just a idea...
I don't know any fork wich does affect the logger.

### What's The Alternative
I don't know a plugin wich is able to move them to a real folder.

**Comment by spannerman79** [comment]
If your logs are getting so large (in the 10MB+ range) then either you should feel proud to have that much activity or if its filled with bugs and errors then this isn't a bungee issue but plugins being used on your bungee instance that is at fault.

Either way - not really a Bungeecord issue.

NB: Most if not all that use Hexacord have in place scripts that do this anyway.  And as you are using a "Server Management Platform" it should be part of that platform anyway as it can be done via shell scripting.

**Comment by xXSchrandXx** [comment]
I know that I can move them by myself after the server stopped, but not every user is able to do that. This is should be a Feature request.

You don't have to add this.

If you won't add this Feature you just close this.
