### ISSUE TITLE
1.14 players can't join

### ISSUE THREAD

**Issue by MayusYT** [HexagonMC/BungeeCord#256]
### What Hexacord version are you using? Post the output of /bungee
![](https://i.imgur.com/fK69xXz.png)

### In addidtion to that, please explain your issue as detailed as possible.
Players that are on version 1.14 and above get an error message that the server doesn't support the version. The Lobby server has viaversion installed, so technically it'd have to work.

![](https://i.imgur.com/82KkwKC.png)

**Comment by i9hdkill** [comment]
You need to use HexaCord for 1.14
