### ISSUE TITLE
Lobby is online but i can't join!

### ISSUE THREAD

**Issue by Jg747** [HexagonMC/BungeeCord#258]
### What Hexacord version are you using? Post the output of /bungee
This server is running McWarriors version git:BungeeCord-Bootstrap:1.14 SNAPSHOT:a53be5e:239 by md_5
Protocol support for 1.7.x by Zartec, ghac and I9hdkill

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
randomhub-1.1.8-SNAPSHOT | multichat-1.7.4 | CommandSyncServer | BungeeReport | BungeeKick

### How can we reproduce the error/bug? 
I don't know. It randomly happens.

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException

### In addidtion to that, please explain your issue as detailed as possible.
When i go on Creative or Factions server with other players sometimes when i do "/hub" it send to me the error "Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException" like the lobby is shutdown. Then i exit the server and i try to login and i can't login for the same error. But the Lobby Server is ON

**Comment by i9hdkill** [comment]
Guess your plugin is sending you to a random server in your config that isn't even online. Pretty sure not a bungee bug. If you can reprodruce it with just BungeeCord, report it upstream
