### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [HexagonMC/BungeeCord#260]
Hi
The following lines have cryptographic API misuses. <br> File name => native/src/main/java/net/md_5/bungee/jni/cipher/JavaCipher.java: Line number => 30: API name => Cipher:First parameter (with value "AES/CFB8/NoPadding") should be any of AES/{CBC, GCM, PCBC, CTR, CTS, CFB, OFB}<BR> File name => native/src/main/java/net/md_5/bungee/jni/cipher/JavaCipher.java: Line number => 37: API name => IvParameterSpec:<BR>

**Comment by spannerman79** [comment]
Send to upstream @mhp0rtal

**Comment by i9hdkill** [comment]
https://github.com/SpigotMC/BungeeCord/issues/2665
