### ISSUE TITLE
Can't connect to a forge server through a Spigot server.

### ISSUE THREAD

**Issue by Casey110405** [HexagonMC/BungeeCord#263]
### What Hexacord version are you using? Post the output of /bungee
git:BungeeCord-Bootstrap:1.14-SNAPSHOT:a80cd78:246 by md_5

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
BungeeChat 2.1.6.855
BungeeEssentials 
BungeeTab List Plus 2.8.10
Discord Chat WM
Discord Bot Api 3.0

### How can we reproduce the error/bug? 
Setup a HexaCord server with a lobby running the latest Spigot 1.14.4, and install the ProtocolSupport plugin. Then create a forge 1.7.10 server with a few mods, then join the server with the mods on the server. It should put you in the lobby and then run /server and attempt to join the modded server.

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
Bungee, Player Disconnected: Timed Out

### In addidtion to that, please explain your issue as detailed as possible.
I have a lobby server with Protocol Support and a modded server with a modpack I made. When I join the server, I join the lobby server like usual. However, when I run /server and connect to the modpack server it just times out in the modded server console and on the client. I know the server works because I can connect to it directly, just not through Bungee. I also don't get kicked from the server, it just says it in chat.

**Comment by spannerman79** [comment]
This is expected behaviour.

Some mods (Like Thaumcraft) need direct access to player NBT data.  The player needs to connect via a forced host  eg modpack.example.com

**Comment by Casey110405** [comment]
Alright, so I did change something. The server runs KCauldron, and I changed bungee=false to true in the spigot.yml file. When I connect to it directly, it says, "If you wish to use IP Forwarding, make sure to enable it in your BungeeCord config as well!". I have IP Forwarding enabled, and I still get kicked when I join from a Spigot server.

**Comment by Casey110405** [comment]
I fixed the issue, I'm stupid and didnt see the forgesupport option in the bungee config, and enabling it fixed my issue. Thanks for the help anyways!
