### ISSUE TITLE
[Proxy] Lost connection to server.

### ISSUE THREAD

**Issue by ShonP40** [HexagonMC/BungeeCord#264]
### What Hexacord version are you using? Post the output of /bungee
Latest ([v246](https://github.com/HexagonMC/BungeeCord/releases/tag/v246))

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
Yes:
BungeeBanRelease, BungeePerms 3.0, BungeeTools-HubCommand-v0.2, BuycraftX, ClientStatus, EzQueueBungee, LiteAnnouncer, Whitelist-1.0.2.

### How can we reproduce the error/bug? 
Put one 1.7.10 player into the same server as an 1.8.9 player.

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
https://pastebin.com/SXjbwyzf

### In addidtion to that, please explain your issue as detailed as possible.
I was playing on the server on 1.7.10 and then someone joined from 1.8.9. As soon as I got close to him (The chunk that he was in, loaded), I got kicked with a message: [Proxy] Lost connection to server.

**Comment by M4T14SG4M3R** [comment]
I have the same problem

**Comment by ShonP40** [comment]
I fixed it a lot time ago.
But I don’t remember how I did it already.
