### ISSUE TITLE
network_compression_threshold

### ISSUE THREAD

**Issue by DanielAlves123** [HexagonMC/BungeeCord#267]
Can I safely change 'network_compression_threshold' to 128 (default is 256) or 64? Will it have good impact on player's connection and small impact on cpu usage? Thanks for help

**Comment by DanielAlves123** [comment]
@spannerman79 it's just a question. I didn't find anything useful using forums. My question is will changing network_compression_threshold from 256 to 128 be helpful and safe? Will value of 64 be better for players?

**Comment by spannerman79** [comment]
Literal 1st, 2nd and 5th result....

![spigotmc](https://user-images.githubusercontent.com/7542384/71236652-965a9d00-2353-11ea-9643-628cebeea083.PNG)

**Comment by DanielAlves123** [comment]
@spannerman79 hehe yes open it and read it. No useful info.

**Comment by spannerman79** [comment]
I have - answers exactly what you asked....

**Comment by DanielAlves123** [comment]
@spannerman79 show me answer to my question.

**Comment by i9hdkill** [comment]
If you lower it, you get more cpu load but packets are smaller. That coould help with latency but doesnt have to. If a ping takes 100ms, its 100ms. Either way, this ticketsfstem is for bugs, not a help section
