### ISSUE TITLE
Versions Below 1.7

### ISSUE THREAD

**Issue by Xuwznln** [HexagonMC/BungeeCord#28]
I use BungeeProtocolSupport and this BungeeCord. The versions below 1.7 will be closed the connection by server.

**Comment by minecrafter** [comment]
Use either ProtocolSupportBungee or this fork.

**Comment by Tim-NL** [comment]
PS Bungee doesn't allow 1.7. (only below) @minecrafter

**Comment by minecrafter** [comment]
Contravening 
https://github.com/HexagonMC/BungeeCord/issues/21#issuecomment-204947894 ?

**Comment by i9hdkill** [comment]
Currently there are two working combinations.
You can either use the up to date BungeeCord (1.8/1.9) with ProtocolSupportBungee to support 1.4-1.9 
OR
our BungeeCord to support 1.7/1.8/1.9 only

**Comment by Xuwznln** [comment]
The latest Bungeecord with BungeeProtocolSupport still can't let 1.7 client to join the Server.And I decided to drop 1.6 and below.

**Comment by James137137** [comment]
I suggest not using BungeeProtocolSupport unless you must have 1.6 or below

**Comment by Tom-III** [comment]
You can now use this BungeeCord and ProtocolSuportBungee together to get 1.4-1.9
