### ISSUE TITLE
Kicked when joining a modded Thermos 1.7.10 server.

### ISSUE THREAD

**Issue by Casey110405** [HexagonMC/BungeeCord#292]
### What Hexacord version are you using? Post the output of /bungee
git:Bungeecord-Bootstrap:1.17-R0.1-SNAPSHOT:31d9e3c:273 by md_5

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
LuckPerms - 5.3.48
Bungeechat - 2.2.3
MyCommand - 5.6.8
BungeeTablistPlus - 3.4.2
DCWM - 3.1.3
Database Drivers - 1.0.0
Discord Bot API - 3.0
### How can we reproduce the error/bug? 
Create a network using Hexacord, and have a lobby (any version) and a modded Thermos 1.7.10 server (on Thermos release 58 Forge 1614) Then attempt to join that modded 1.7 server with a modded 1.7 client.

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
No errors in console, only shows connecting then disconnecting.

### In addition to that, please explain your issue as detailed as possible.
I have a Lobby running paper 1.12.2, Hexacord running version 273, and a Thermos 1.7.10 server running version 58. I removed the Thermos server from the Bungee network and joined it as its own server, and it works completely fine like that. But, when I attempt to join it from within the network, it will attempt to join then put me back in the Lobby and say the server you were previously on went down, but it didn't. I then try to join again, then my client will kick me from the server entirely and say fatal error has occured, this connection is terminated. On my Thermos server, it shows where I'm joining in and my Lobby shows where I left. Bungee also shows the transfer, but then it says UpStream bridge disconnected, then DownStream bridge disconnected <-> RTSPS1 (Thermos Server).

**Comment by spannerman79** [comment]
What mods do you have running on the Thermos server?

I know for some mods you need to use direct connect otherwise you will get those error messages.

**Comment by Casey110405** [comment]
I have like 150+ mods, so I can’t really list them all, but I will say it worked before I updated my Hexacord to the version to support 1.17. I haven’t changed the mods at all, it worked before but now it doesn’t.

**Comment by Sir-Will** [comment]
Same issue here. Updated from build 268 to 274 and trying to join an infinity modpack server via forced hosts results in the `java.io.IOException: Connection reset by peer` error.

Something between these builds changed, which broke 1.7.10 support.

**Comment by spannerman79** [comment]
[This](https://github.com/HexagonMC/BungeeCord/pull/296) PR was merged.

Check to see if it resolves the issue for you @Casey110405 & @Sir-Will

**Comment by Sir-Will** [comment]
Build 277 is working again.
