### ISSUE TITLE
Too Many Plugin Message Channels Registered Error

### ISSUE THREAD

**Issue by Column01** [HexagonMC/BungeeCord#299]
### What Hexacord version are you using? Post the output of /bungee

```
14:36:44 [INFO] This server is running HexaCord version git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:2a722b0:278 by md_5
14:36:44 [INFO] Protocol support for 1.7.x by Zartec, ghac and I9hdkill
```

### Are you using Bungee plugins? If yes, please list all of them + versionnumber

- BanManagerBungeeCord v7.5.0
- BungeeTablistPlus v3.4.4
- LuckPerms-Bungee v5.3.61
- NuVotifier v2.7.3
- Plan v5.4
- 2 Custom plugins that I'm not listing (no errors from them)

### How can we reproduce the error/bug? 

1. Install the latest HexaCord
2. Add a forge server to it
3. Try to connect
4. Error

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
https://gist.github.com/Column01/3405beebb17d446cb425af5543ced120

### In addidtion to that, please explain your issue as detailed as possible.

When using the latest HexaCord, we've discovered our forge servers (ATM only 1.7.10 servers) have an issue where they have "too many registered plugin channels" and we get disconnected when trying to connect. I'm not sure if this happens with other forge versions but I imagine it's not limited to 1.7.10 due to the nature of how forge support works. The last build we used was `git:BungeeCord-Bootstrap:1.17-R0.1-SNAPSHOT:81bbf85:277` and we didn't have issues. I'm assuming it's a BungeeCord issue, PaperMC added a config option to Waterfall for adjusting the number of channels allotted (see https://github.com/PaperMC/Waterfall/issues/701)

**Comment by johnfriedrich** [comment]
Thanks, added a limit config option similiar to Waterfall. Please give latest Build a try

**Comment by Column01** [comment]
Trying it out now, thanks for the speedy reply!

**Comment by Column01** [comment]
Looks to be working as intended! Thanks so much :D
