### ISSUE TITLE
Latest version bad packet ID.

### ISSUE THREAD

**Issue by ManiecTV** [HexagonMC/BungeeCord#38]
`08:28:42 [INFO] [ManiecTV] <-> ServerConnector [lobby] has connected
08:28:45 [WARNING] [ManiecTV] -> UpstreamBridge - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.KeepAlive 0 Protocol GAME Direction TO_SERVER
08:28:45 [INFO] [ManiecTV] disconnected with: DecoderException : net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.KeepAlive 0 Protocol GAME Direction TO_SERVER @ io.netty.handler.codec.MessageToMessageDecoder:99
08:28:45 [INFO] [ManiecTV] -> UpstreamBridge has disconnected
08:28:45 [INFO] [ManiecTV] disconnected with: [Proxy] Lost connection to server.
08:28:45 [INFO] [ManiecTV] <-> DownstreamBridge <-> [lobby] has disconnected`
# http://pastebin.com/yhCgCX9i

i have this error on latest version can repair it?

**Comment by i9hdkill** [comment]
Are you using Build 62? Which minecraft client version? Forge mods installed? If yes, which mods?

**Comment by ManiecTV** [comment]
I used version 53 and no errors , while version 62 is above error

**Comment by ManiecTV** [comment]
Can help?

**Comment by ghacproductions** [comment]
@ManiecTV Is this still relevant?

**Comment by ghacproductions** [comment]
Closing as no answer from original poster. Reopen issue if problem still persists.
