### ISSUE TITLE
MC 1.10

### ISSUE THREAD

**Issue by Proplex** [HexagonMC/BungeeCord#41]
I apologize for asking so soon, but do you have intentions of supporting 1.10 as well? We rely heavily on your BungeeCord fork, and it would be wonderful if you did.

Thanks.

**Comment by ghacproductions** [comment]
I just updated our fork with the origina one, please try v63+ for 1.10 support. Please inform us about errors appearing.

**Comment by James137137** [comment]
there is no v63+ yet XD

**Comment by Proplex** [comment]
I compiled it myself, I've attached it to this comment.
Bunge
[HexaCord 1.10 Support.zip](https://github.com/HexagonMC/BungeeCord/files/306252/HexaCord.1.10.Support.zip)

**Comment by ghacproductions** [comment]
Build failed, not quite sure why. However, here it is:

[v63](https://github.com/HexagonMC/BungeeCord/releases/tag/v63)

**Comment by ghacproductions** [comment]
Closed. Please open a new issue when errors are occouring.
