### ISSUE TITLE
IOException: An existing connection was forcibly closed by the remote host 

### ISSUE THREAD

**Issue by Fluxty** [HexagonMC/BungeeCord#48]
Hey,

First off I want to say this is an awesome fork! The only issue, and I'm not 100% sure this Bungeecord is the culprit, is that from time to time everyone on the server is disconnected with error message "IOException: An existing connection was forcibly closed by the remote host "

This happens at least once a day, up to two times. I'm assuming it's the Bungee jar because everyone on the server is kicked, regardless of where they are playing, and the issue began before any Bungee plugins were installed.

**Comment by i9hdkill** [comment]
Hi,
are you hosting on a vps? They tend to be quite weak and dropping connections if the proxy reaches a specific playercount.

**Comment by i9hdkill** [comment]
Closing this - no answer

**Comment by Fluxty** [comment]
Hey, I know this response is extremely delayed, the disconnects are pretty infrequent now so they haven't put up that much of an issue until now. Here's the error in console when players are disconnected:

`disconnected with: §fNativeIoException : syscall:read(...)() failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1`

I'm on a dedicated server through Ready2Frag, no VPS. It doesn't seem to have any correlation with player count, it happens on occasions whether we have 5 online or 25. We completely reinstalled linux (for a different issue) and this one is still here. I'm assuming it's probably something with our host but I'm not an expert here, was wondering if I could get your input.
