### ISSUE TITLE
Empty packet issue in 1.7

### ISSUE THREAD

**Issue by Tom-III** [HexagonMC/BungeeCord#5]
When switching servers in 1.7 clients the following happens sometimes.

```
03.03 20:42:40 [Server] INFO io.netty.handler.codec.CorruptedFrameException: Empty Packet! 
03.03 20:42:40 [Server] INFO at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:36) 
03.03 20:42:40 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:360) 
03.03 20:42:40 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) 
03.03 20:42:40 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) 
03.03 20:42:40 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) 
03.03 20:42:40 [Server] INFO at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152) 
03.03 20:42:40 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) 
03.03 20:42:40 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) 
03.03 20:42:40 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) 
03.03 20:42:40 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823) 
03.03 20:42:40 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339) 
03.03 20:42:40 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255) 
03.03 20:42:40 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) 03.03 20:42:40 [Server] INFO at java.lang.Thread.run(Thread.java:745) 
03.03 20:42:40 [Server] squirrelmail disconnected with: CorruptedFrameException : Empty Packet! @ net.md_5.bungee.protocol.Varint21FrameDecoder:36 03.03 20:42:40 [Server] disconnected with: [Proxy Lost connection to server. 
03.03 20:42:40 [Server] <-> DownstreamBridge <-> [Hub has disconnected]
```

**Comment by Zartec** [comment]
Normal builds or ProtocolHack?

**Comment by Zartec** [comment]
Cant reproduce. Works fine with [v23+](https://github.com/HexagonMC/BungeeCord/releases/latest)

Please try it again with this version.

**Comment by Tom-III** [comment]
On serverside are servers with ProtocolSupport plugin to allow 1.8 and 1.7 on 1.8 server

**Comment by i9hdkill** [comment]
Did you try our latest release? If you use ProtocolSupport to allow 1.8 on 1.7 servers, I would recommend you using spigot Build 1649 (Protocolhackbuild)
This allows 1.8 and 1.7 without plugins.

**Comment by Porama6400** [comment]
ProtocolSupport is better?

you can install on lastest spigot so it more stable?

**Comment by i9hdkill** [comment]
It has unwanted sideeffects like not working holograms etc. In the end it's your decision.

**Comment by Tom-III** [comment]
ProtocolSupport allows 1.7 on a 1.8 server, NOT 1.8 on a 1.7 server.  Now it also allows 1.7 AND 1.8 on a 1.9 server.

**Comment by Porama6400** [comment]
what is Varint21FrameDecoder class?

i hope you can fix this problem :D

**Comment by Zartec** [comment]
The Varint21LengthFieldPrepender prepends the sent packet with an varint defining the size of the packet.

The Varint21FrameDecoder reads the varint and the the size defined by the varint.

This error can occur after every packet that is sent with wring data in it.

We definitely need more info of the error.
- Occurs when switching between?
- Server versions
- Plugins modifying the protocol (ViaVersion, ProtocolSupport, ...)
- Modded server (Forge, ...)
- Modded client (Forge, ...)
- Bungee version
- Bungee plugins that change the behavior of reconnect or protocol

As many infos as you can give. Because i already said that we cant reproduce the error.
