### ISSUE TITLE
[Bug] Client crash when changing server

### ISSUE THREAD

**Issue by Rubbertjuh** [HexagonMC/BungeeCord#56]
Hello,

Before I describe the bug. I would like to say that I really appreciate all of your hardwork that you put into this project.
I've been having this issue for months now and have tried numerous forks of Bungeecord. I've tried Waterfall, Travertine, normal bungeecord but none fixed the issue.
That's why I'm not 100% sure if its just related to Bungeecord or that the mods are at problem.

I'm running the modpack Tekkit Legends and whenever a client executes the command /server survivala or any other server. Or when you execute /send <player> <server>  via the console, if the player is near modded items (like an EMC farm), the client will crash completely. 
This only happends when the client is near modded items. I think it has something to do with (Ticking) Tile Entities. 
I made a zip including all the client crashes I received so far. 
All the crashes inside the zip are reproduced.
https://mega.nz/#!Ll4DEaQb!te0nSFVq14Y56zQ3zdxatH0V-059BbavKXZBNBCrPOE

Latest 2 crashes on Hexagon:
http://hastebin.com/sawaluwote.1c
http://hastebin.com/imoqevabes.1c
http://hastebin.com/yotasitizu.1c

**How to reproduce this on your own server?**
1.Create a Tekkit Legends server.
2.Set up Hexagon 
3.Set everything up like you usually do.
4.Built a modded house.
5.Switch to another server connected to the bungeecord.
6.Client will crash

If this is not related to Bungeecord somehow, I would really appreciate any feedback on this issue. It's been buggering me for a long time and any feedback is much appreciated. 
Things I've been wondering:
Why is this happening?
Where is it coming from?
If it's not the bungeecord, how do I fix this?

Thank you for reading this bug report and I hope someone can help me out with this.

Edit: Running latest Hexagon version.
Running CB 1.7.10 - Thermos (Fork of Cauldron)

**Comment by i9hdkill** [comment]
Hey,
thanks for the precise report.
Is this crash happening with Yives BungeeCord (tcpr mirror site) aswell?

If no, we could go through the diffs to look for the issue.
Otherwise it could get quite hard.

**Comment by Rubbertjuh** [comment]
Hello, 
Thank you for the swift reply. 
Unfortunately, on a clean Bungeecord server. This also occurs. 
I do not have any crash logs of this at the moment though. 

I invite you to join my server so you can see how this happends for yourself if you want.

**Comment by i9hdkill** [comment]
Please try this build:
http://gogs.tcpr.ca/TCPR/Fixes/src/master/BungeeCord

**Comment by Rubbertjuh** [comment]
This is the second build I tried, I believe this also had the same issue. 
I tried Regular bungeecord, thermos fixed version, watefall, travertine, Hexagon

I will try again when I get home though, just to make sure. But I don't think this changes anything.

**Comment by Rubbertjuh** [comment]
Do you want me to provide more crash logs? I can provide more and update this thread on the way.

**Comment by i9hdkill** [comment]
To be honest, I doubt that we are able to fix this issue.
@ghacproductions ?

**Comment by Rubbertjuh** [comment]
That would really be a bummer. I'm willing to spend a lot of money, to get this fixed.

**Comment by ghacproductions** [comment]
Is this error still present?

**Comment by Rubbertjuh** [comment]
Yes, still very desperate to fix it

**Comment by ghacproductions** [comment]
Is there anything special to do when setting up a Tekkit Legends server? I set up one but was not able to connect via BungeeCord.

**Comment by Rubbertjuh** [comment]
What was the error that you got when connecting? I did not have to set up anything special with Tekkit Legends or Bungeecord in order for it to work. Just the usual setup. 

I'm currently on vacay, but can help you more via Discord if needed?

**Comment by ghacproductions** [comment]
There was no error at all, it just tried to connect all the time and did not even get a timeout, joining directly (without BungeeCord) is no problem. I'll try this again later.

**Comment by Rubbertjuh** [comment]
Port issue maybe? Can you test it with vanilla?

**Comment by ghacproductions** [comment]
Vanilla and Spigot work fine. It's just not working with Tekkit Legends.

**Comment by ghacproductions** [comment]
Ok, I got it working now. What items are causing this problem?

**Comment by i9hdkill** [comment]
Does the client try to connect to the server you specified with /server xxxx? Any error on that server?
Does this problem also occurs when switching from one tekkit legend server to a second tekkit legend server when using /server?

**Comment by ghacproductions** [comment]
@Rubbertjuh Please answer the questions.

**Comment by Rubbertjuh** [comment]
Sorry for the silence. been on 3 week holiday. 
Seems that this issue somehow magically fixed itself... Might have to do with our setup. 
If it happens again, I will reopen this issue. For now, see it as closed.
