### ISSUE TITLE
Get Disconnected When I Talk On Another Server

### ISSUE THREAD

**Issue by BungeeTheCookie** [HexagonMC/BungeeCord#59]
Whenever I talk on another server, I am getting disconnected. When I am talking on the hub, I am fine, but if I do /server <serverName> and speak, I get disconnected with that error.

http://pastebin.com/F5UmYHtj

**Comment by ghacproductions** [comment]
What BungeeCord and Spigot version are you using?

**Comment by BungeeTheCookie** [comment]
@ghacproductions I am using the latest version of HexagonMC, a 1.10 Hub using ProtocolSupport, running 1.7.10 Thermos servers.

**Comment by BungeeTheCookie** [comment]
Do you know what the issue may be?

**Comment by i9hdkill** [comment]
Are you using a spigot-side chat plugin or bungee-wide chat plugin in your thermos server?

**Comment by BungeeTheCookie** [comment]
I am using ChatControl Pro to handle my messages @i9hdkill . It is spigot-side.

**Comment by BungeeTheCookie** [comment]
When i was using an old version of Waterfall (1.7 - 1.9) chat worked fine, I just got random disocnnects here and there. I switched to Travertine but every time I talked on another server I crashed with a **different message.** I switched to HexagonMC to see if I could chat but I'm crashing with this new message.

**Comment by BungeeTheCookie** [comment]
Is there a way to fix this?

**Comment by BungeeTheCookie** [comment]
@ghacproductions @i9hdkill Is there a way to fix this?

**Comment by i9hdkill** [comment]
Basically make sure your Bungee plugins are built against 1.10 and your 1.7.10 plugins are up to date.
Does this even happen if you use the vanilla minecraft server chat? (Chat plugin disabled)

**Comment by BungeeTheCookie** [comment]
@i9hdkill Let me try and see.

**Comment by BungeeTheCookie** [comment]
@i9hdkill I have tried it using a clean Thermos server. The error only occurs when ChatControl Pro is installed.

**Comment by i9hdkill** [comment]
Not a Bungee issue

**Comment by BungeeTheCookie** [comment]
@i9hdkill It is weird because I was able to chat on the Old version of Waterfall (1.7.10 - 1.9), but let me talk to the ChatControl dev and see what he says
