### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by franciscopaniskaseker** [HexagonMC/BungeeCord#60]
I have had high CPU usage using HexagonMC (the same with last bungeecord vanilla). 

I have only one plugin with HexagonMC bungeecord what do:
- special permissions for each server
- announcer (each 5min)
- lobby teleport (on demand event)

I observed that consume:
- 140 players +- 80%
- 500 players +- 200%
- 700 player +- 450%

And yees, this is not proportional!

I think that is too much to only proxy connections. Am I wrong?

(1) What kind actions (GC, Java debug etc) I can do to verify what is the problem (if I have a problem)?
(2) Why bungee use too much cpu resources? I would like to address main bungee resources that need a lot fo CPU to, if it is possible, help tweak them in code.

Today I use last mainline kernel with last stable CentOS. I tested last oracle and openjdk javas (stable) and I verified same issue. I have a lot of memory and zero swap (I use swapiness zero too).

With HexagonMC I use these parameters:
 -XX\:+PrintGCDetails -XX\:+PrintGCTimeStamps -XX\:+UseG1GC -XX\:MaxGCPauseMillis=50 -XX\:ParallelGCThreads\=8

I already tried:
- Xms 1024 Xmx 5192
- Xms 16000 Xmx 16000
- Change MaxGCPauseMillis (50 to 250)
- ParallelGCThreads (2 to 8)
- Tests with G1GC and CMS

Usually GC is the java feature that consume a lot of CPU usage, but even setting a lot of memory to have less GC events I do not have better result.

Thank you for all help and let make HexagonMC better than vanilla =)

**Comment by i9hdkill** [comment]
Hi,
first of all thanks for using HexaCord, however it's the wrong area for looking for help in your specific case.
Head over to the spigot forums, more specific here:
https://www.spigotmc.org/forums/bungeecord-help.70/
There are plenty of people that might help you better than we can:)

Btw: We are just using "-XX:+UseG1GC -XX:G1HeapRegionSize=4m -Dio.netty.recycler.maxCapacity.default=20000"
That worked for up to 250 players @100-150% (Never reached more, so can't really tell if these flags are good or not in your situation)
Usually, a bungee shouldn't hold more than 400 players, might be better to split into 2-3 different bungees.
