### ISSUE TITLE
Bot Attack : every crash

### ISSUE THREAD

**Issue by EverTzExo** [HexagonMC/BungeeCord#63]
Hello everyone,
I get on my server bots that are constantly crashing, I thought it was patched but apparently not .. http://pastebin.com/DaaS7GBQ

**Comment by i9hdkill** [comment]
Bots are sending invalid data. Can your reproduce that on the original 1.8-1.10 bungee?

**Comment by EverTzExo** [comment]
I can not try because my server is 1.7.10

**Comment by manercraft** [comment]
It's similar to https://github.com/HexagonMC/BungeeCord/issues/20

**Comment by i9hdkill** [comment]
Are you running an offline mode server?

**Comment by EverTzExo** [comment]
yes, french server

**Comment by Donitovan** [comment]
Themos ?

**Comment by i9hdkill** [comment]
We do not support offline mode servers.
