### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by Darko266** [HexagonMC/BungeeCord#64]
Hello,

I dont know if its a Bug or something

But someone can crash the proxy with something (i dont know the name) and all players disconect just the proxy crashes

This is happenig in the last V84 Update

Please help
Thanks

**Comment by MJRLegends** [comment]
Could you supply a copy of that crash from the logs?

**Comment by Darko266** [comment]
I dont know becouse it is 3 hours away 
Its this maybe [Proxy] Lost connection to server.
or THIS : 14:03:10 [WARNING] [xPew] -> UpstreamBridge - IOException: syscall:read(...)() failed: Connection reset by peer
14:03:10 [INFO] [xPew] disconnected with: §fNativeIoException : syscall:read(...)() failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1

**Comment by i9hdkill** [comment]
We need the full bungee log.

**Comment by Darko266** [comment]
I cannot upload it to pastebin.com
http://www.mediafire.com/download/mka40q1jmfzt2dz/LOg.zip
There :)

**Comment by Darko266** [comment]
It starts somewhere at 14:00 i think or look al the log please 

Thanks

**Comment by Darko266** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/20874142/17461321/cded0d38-5c88-11e6-8ad1-5fea9b602370.jpg)
It happend again, see the SS

**Comment by Darko266** [comment]
http://pastebin.com/qQNAHwEs
This happend when it crashes

**Comment by MJRLegends** [comment]
From that log you have posted in the message above ir looks like its erroring on a database statement/call

**Comment by i9hdkill** [comment]
Not a bungee issue. Misconfigured litebans.
