### ISSUE TITLE
Bad packet ID when attempting to use any Mods

### ISSUE THREAD

**Issue by Nitroholic** [HexagonMC/BungeeCord#66]
18:28:01 [INFO] Null type for id: 4242
18:28:01 [WARNING] [Nitroholic_] <-> DownstreamBridge <-> [Modded] - bad packet ID, are mods in use!? Did not read all bytes from packet class me.Leftwitch.BungeePacketAPI.Packets.Inventory.PacketPlayOutSetSlot 47 Protocol GAME Direction TO_CLIENT
18:28:01 [INFO] [Nitroholic_] <-> DownstreamBridge <-> [Modded] has disconnected
18:28:01 [INFO] [Nitroholic_] <-> ServerConnector [Lobby] has connected
18:28:01 [INFO] [Nitroholic_] disconnected with: Â§cKicked whilst connecting to Lobby: Â§fOutdated client! Please use 1.9.2
18:28:01 [INFO] [Nitroholic_] <-> ServerConnector [Lobby] has disconnected

Cannot connect to server with 24 loaded mods. As soon as any modded item enters inventory, I experience this disconnect. Unable to reconnect to server unless usercache is reset. 

Would like to note that when the user connects to the Bungee, they are routed to a vanilla 1.7.10 Spigot server which they then can connect to the Modded server via. I couldn't find a way to directly connect to the Modded as it would give a IP Forwarding error and I use KCauldron as appose to Sponge as there is no 1.7.10 Sponge.

I use the latest build of your BungeeCord version.

Server contains:
Baubles-1.0.1.10
BigReactors-0.4.3A
Botania r1.8-249.jar
BrandonsCore-1.0.0.12
CodeChickenCore-1.7.10-1.0.7.47
CoFHCore-3.1.2-325
CoFHLib-1.1.1-181
Draconic-Evolution-1.7.10-1.0.2g
EnderCore-0.2.0.36_beta
EnderIO-2.3.0.427_beta
EnderStorage-1.4.7.37
EnderTech-0.3.2.405
FTBLib-1.0.18.3
FTBUtilities-1.0.18.3
ImmersiveEngineering-0.7.7
immersiveintegration-0.6.8
MineFactoryReloaded-2.8.2B1-188
TConstruct-1.8.8
ThermalDynamics-1.2.0-171
ThermalExpansion-4.1.2-240
ThermalFoundation-1.2.4-114

**Comment by i9hdkill** [comment]
Can you pls try using this Bungee fork?
http://gogs.tcpr.ca/TCPR/Fixes/src/master/BungeeCord
Does the issue still persists with that fork?

**Comment by Nitroholic** [comment]
This is extremely outdated... I'm not trying this on my server. It doesn't support 1.8+ and half of my playerbase is that.

**Comment by Nitroholic** [comment]
Edit, some Items work, some items kick the user. -.-

**Comment by i9hdkill** [comment]
Some forge mods are doing weird stuff with packets, like negative packets and other things. BungeeCord cannot handle that. We can't fix this bad behaviour on our site because we don't know what kind of packets these mods are using exactly.

**Comment by Nitroholic** [comment]
Don't worry, I found the issue. It was caused by another Bungee plugin called Friends which was sending packets. Thi/ caused the issue. Thanks for all of your support though!
