### ISSUE TITLE
1.7.10 kcauldron not logining in. timeout

### ISSUE THREAD

**Issue by popcorn9499** [HexagonMC/BungeeCord#67]
I have found that when i tried to run this bungeecord that 1.7.10 forge running under kcauldron doesnt work well. it just wont connect via the client. i found this happened on v86. v84 works fine though. there was rlly nothing special in the logs it just started the connection but never acutally logged the player in. so im thinking its something that got changed in the connection handler becuz i removed all plugins and it still happened. even ran vanila kcauldron no plugins or mods same thing.

If you could respond with what u need id be very happy to send it. im unsure logs would even be useful here but ill send them

[Kcauldron Log](http://pastebin.com/sst6KgJ6)
[Bungee Log](http://pastebin.com/kNkd1tep)

**Comment by MJRLegends** [comment]
Yeah im getting the same issue

**Comment by ghacproductions** [comment]
I'm looking into this. one moment please.

**Comment by ghacproductions** [comment]
As this error also occurs on the BungeeCord from SpigotMC when trying to connect to a 1.8 Sponge server, this is most likely an error in the original BungeeCord. We will open a new issue in a few moments.

**Comment by MJRLegends** [comment]
yeah i think the commit 3a0b0aa116310add15ef0b2d77be8b76a1564adf messed it up

**Comment by i9hdkill** [comment]
Yes you are right:
https://github.com/SpigotMC/BungeeCord/issues/1932

**Comment by ghacproductions** [comment]
In Version [v88+](https://github.com/HexagonMC/BungeeCord/releases/download/v88/BungeeCord.jar), a new config option `always_handle_packets` was added. This config option defaults to `false`:

`always_handle_packets: false`

If you set this value to true, all packets will be handled what should fix your issue. Please report any issues occuring.
