### ISSUE TITLE
Forced Hosts

### ISSUE THREAD

**Issue by WinggedPhantom** [HexagonMC/BungeeCord#71]
Hi, I'm having issues using forced hosts, it either times out or says a bungeecord ipforwading issue when connecting. I'd like to be able to have play.mydomain.com go to my hub and then have s2.mydomain.com direct connect to my 2nd server without needing to connect to the hub first. Also i'm using SpongePLS and the 2nd server is running on 1.7.10 with forge. 
Bungee config: http://pastebin.com/Y3pfHnBN
DNS Config: https://gyazo.com/b8e0dfcf5dcabe041fe1e50967b2bddb
Reply if you want me to add the unedited versions (versions without ip's and server name removed)

**Comment by ghacproductions** [comment]
Can you test it with this version please?

https://github.com/HexagonMC/BungeeCord/releases/download/v84/BungeeCord.jar

**Comment by MJRLegends** [comment]
@ghacproductions i can confirm it works with v84 as i use it myself and had the same issue with v86

**Comment by WinggedPhantom** [comment]
@ghacproductions @MJRLegends Thanks for the help it worked with this version, another issue I had was that when one of my servers went down it would disconnect them instead of just sending them to the hub. Not sure if this older version fixes that issue or not since I haven't tested yet.

**Comment by ghacproductions** [comment]
Then please test this.

**Comment by Eufranio** [comment]
Confirm it works with v84. Why not the newest versions?

**Comment by WinggedPhantom** [comment]
@ghacproductions can confirm it disconnects players on restarts instead of sending them to the hub.

**Comment by ghacproductions** [comment]
Some changes made by in the original BungeeCord broke up a lot of stuff. I'll add a config option for this later this day.

**Comment by MJRLegends** [comment]
Why not just remove them?

**Comment by ghacproductions** [comment]
The change that broke some things up also fixed another issue.

Check this out:
https://github.com/SpigotMC/BungeeCord/issues/1930

**Comment by ghacproductions** [comment]
In Version [v88+](https://github.com/HexagonMC/BungeeCord/releases/download/v88/BungeeCord.jar), a new config option `always_handle_packets` was added. This config option defaults to `false`:

`always_handle_packets: false`

If you set this value to true, all packets will be handled what should fix your issue. Please report any issues occuring.
