### ISSUE TITLE
Spike Lags occuring due to Garbage Collector

### ISSUE THREAD

**Issue by prajniak** [HexagonMC/BungeeCord#75]
Good afternoon,

I am system administrator on network with pixelmon 3.5.2 and we are running into issues, which seems to indicate memory leak. The CPU goes above 200% on "top" while Garbage Collector tries to release RAM but when it does it, it is a usually very small amount. 

Adding more RAM for Bungee just delays the problem. I have tried to removing plugins from BungeeCord if they are they are the cause of memory leak. 

We are running 2 bungees with redisbungee and using Hexagon. I have ran JProfiler on Bungee to further determine cause. I also tried to use different GC like G1 or CMS but it did not helped at peak. 
Attaching pictures from JProfiler under post. 

The plugins we are using - MultiLobby, RedisBungee, BetterServerJoin, BungeeKick, ProxyPipe-BungeeCord, UltimateFriends, BungeeRTK. Currently we restart every both bungees 24 hours.

If you could provide some advice or any help, I would be very grateful.

Have a nice day.

Best regards
Patrik Rajniak

http://i.imgur.com/p51dJFS.png
http://i.imgur.com/vLA99S0.png
http://i.imgur.com/Ta12hTI.png

**Comment by ghacproductions** [comment]
Hello,

I'm just curious, how many players does every of the 2 BungeeCord-servers handle?

Greets,
ghac

**Comment by prajniak** [comment]
Network has capacity of 1 000 and currently we have 870 players and currently we have 450 players on one bungee and second bungee has 420 players.

Thank you for quick reply

**Comment by ghacproductions** [comment]
Have you also had 400+ players on the original BungeeCord (when there was 1.7 support built-in), and if so, did you also have those lag-spikes?

**Comment by prajniak** [comment]
I havent been administrator back then for the network but previous administrator reports that the problem started to occure when upgrading on 1.7. On 1.6 they had to restart bungee only once per week. Since the 1.7 upgrade the bungee has problems with lagspikes also when we did not have redis and on original BungeeCord.

The second bungee was installed only because of the lag spikes but it still only delays the problem as adding RAM does.

**Comment by ghacproductions** [comment]
Well, I guess, as this also occured when you used the original BungeeCord, that issue is not really on our end. We have not done a lot things on our version except readding support to 1.7, so that most likely has to be an issue with the BungeeCord from SpigotMC. You might want to report the issue there as it may also influence other networks.

**Comment by prajniak** [comment]
Alright, I kinda thought but I need to take care of all ends just in cause.

Once again, I am thankful for investing time and trying to help. Gonna try to post issue there.

**Comment by ghacproductions** [comment]
No problem.
