### ISSUE TITLE
Red Cross - Incompatible fml modded server 0 mods present

### ISSUE THREAD

**Issue by Rubbertjuh** [HexagonMC/BungeeCord#76]
Hello,
Usually, when you enable Ping-pass-through, the Red cross that says: "incompatible fml modded server 0 mods present", will go away.
Otherwise known as the "Red cross" : https://gyazo.com/28d7ae0d4458e24505a438da32cd9c22
How did you all go about fixing this issue? Also with ping-pass-through ?

This issue came to light when I came back from my vacation, unsure when it started. I am sure that it was solved when I ran normal Bungeecord though, I am not sure if this is related.
I'm seeking for advice as this is scaring a lot of potential players away

Thank you for reading this and thank you for assisting me on this matter.

**Comment by Time6628** [comment]
Can confirm. 
There's an old github issue on the bungeecord repo explaining why this happens, https://github.com/SpigotMC/BungeeCord/issues/1505#issuecomment-124738733.

**Comment by Rubbertjuh** [comment]
Adding more information:
My backend default server is a Tekkit Legends server 
Confirmed to show on version .82+ (Haven't tested below)
If you need more information, please tell me.

**Comment by Yann151924** [comment]
I use this : https://www.spigotmc.org/resources/bungee-forgeicon.17695/ , it can be a solution if you want.
And i choose the bukkit icon (not red cross for the player :) )

**Comment by Eufranio** [comment]
Thank you!

**Comment by Rubbertjuh** [comment]
Thanks a bunch! Closing this issue now as it is resolved ;)
