### ISSUE TITLE
Delays on Sponge server

### ISSUE THREAD

**Issue by OblivionNW** [HexagonMC/BungeeCord#77]
When using this to allow clients to connect to a Sponge server they experience delays.
For example, if someone says 'Hello' in chat the other players will see this message ~60 seconds later. This issue only arose after I began using your fork of Bungeecord. The issue only occurs on my Sponge servers, players connecting to Bukkit or Cauldron servers don't experience this delay

**Comment by ghacproductions** [comment]
Does this delay only occur when chatting? Or also when using commands etc.?

**Comment by i9hdkill** [comment]
Could you please confirm that with the latest BungeeCord build and the latest HexaCord build?

**Comment by i9hdkill** [comment]
Not an issue of HexaCord. Running a sponge setup without issues.
