### ISSUE TITLE
Quick Question About Packets Setting

### ISSUE THREAD

**Issue by Fluxty** [HexagonMC/BungeeCord#78]
Is there a more advanced explanation of the packets setting? Players are being kicked by viaversion for sending too many packets, I think I have some kind of plugin incompatibility. If I disable that feature and use this Bungeecord setting could that potentially solve my issue?

I don't really understand the setting.

**Comment by i9hdkill** [comment]
Open your ViaVersion config and increase maxpackets. This solves your problem. It's not Bungee related.
