### ISSUE TITLE
Player being kicked with lost connection

### ISSUE THREAD

**Issue by CzlowiekKuktas** [HexagonMC/BungeeCord#81]
Hi, 1.7.10 players are kicked with "Lost connection" message. Same was on Waterfall-old and Travertine.

**Comment by MJRLegends** [comment]
Yeah im getting the same issue, what host are you using or where are you hosting them?

**Comment by CzlowiekKuktas** [comment]
What's the difference?

**Comment by MJRLegends** [comment]
Because this is normally a host issue so if we are using the same host then we know the issue...

**Comment by CzlowiekKuktas** [comment]
This is proxy's issue.

**Comment by MJRLegends** [comment]
I've only be getting it in the last 2 days and have tired different bungeecords so are you using SoYouStart/OVH host??

**Comment by CzlowiekKuktas** [comment]
There is no difference. Normal BungeeCord is not having this issue, there is a problem in proxy.

**Comment by MJRLegends** [comment]
@ghacproductions any thoughts as im getting this issue to and its stressing me out

**Comment by i9hdkill** [comment]
It's very unlikely a proxy issue. Any errors cauldron/spigot side when the player gets the disconnect?

**Comment by MJRLegends** [comment]
@i9hdkill nope dont think so just messages saying time out or [Proxy] Lost connection to server,

i have my dedicated server hosting company look at if im getting ddosed and they said its fine and im getting low traffic and nothing has changed with my servers since and not anywhere near when this started.....

**Comment by MJRLegends** [comment]
Also i've tried this bungeecord and two others and still happens, im really confused to why its happening and idk what the problem is

**Comment by MJRLegends** [comment]
@i9hdkill In the console im getting errors such as "[Netty Client IO #12/ERROR]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException"

**Comment by i9hdkill** [comment]
Definetely a host issue. Ovh and resellers are known to have such networks issues from time to time.

**Comment by MJRLegends** [comment]
Yeah they claim nothing is wrong with my servers connection though @i9hdkill

**Comment by MJRLegends** [comment]
@i9hdkill idk what the issue is? and any chance some debug messages could be added to a custom build to help find my issue?

**Comment by Eufranio** [comment]
@MJRLegends do you have SkinsRestorer?

**Comment by MJRLegends** [comment]
Never heard of it so i dont think so

**Comment by MJRLegends** [comment]
@i9hdkill im currently in a standalone vanilla server and my servers connected to the bungeecord are having issues with time outs but im still in this standalone vanilla server, so the issue is something with the bungeecord, i've even tried to run it without any plugins on the bungeecord, if anything it makes it worse.....

**Comment by i9hdkill** [comment]
Could you please try to reproduce this on your local machine?

**Comment by MJRLegends** [comment]
I havent tried yet....

**Comment by MJRLegends** [comment]
Im trying to change back something someone told me to do to my mod pack servers that use thermos, they told me here https://github.com/CyberdyneCC/Thermos/issues/522 it was to change the timeout-time in the spigot.yml from 90 to 9000

**Comment by Eufranio** [comment]
Did you set player-throttle to -1 in bukkit.yml?

**Comment by MJRLegends** [comment]
@Eufranio yeah?

**Comment by MJRLegends** [comment]
My test of 

`Im trying to change back something someone told me to do to my mod pack servers that use thermos, they told me here CyberdyneCC/Thermos#522 it was to change the timeout-time in the spigot.yml from 90 to 9000`

didnt do anything i dont think

**Comment by Eufranio** [comment]
Timeout-time is the time before **the server** crash, not the players, there is something wrong with your configs. Try run /debug start in the spigot server before get kicked and paste the results.

**Comment by MJRLegends** [comment]
@Eufranio after doing /debug start i got this http://pastebin.com/bxDsvGnx

**Comment by MJRLegends** [comment]
players are defo saying they are getting it in the hub server too which is a spigot server not modded server

**Comment by CzlowiekKuktas** [comment]
That'z weird. Why do you think that it's hosting problem, when normal BungeeCord doesn't have this problem? There is nothing in the console, I started an issue in the old Waterfall, this is the reason they deleted it and removed 1.7 support, but the problem is still existing on the Travertine.

**Comment by MJRLegends** [comment]
Because i didnt post that it does work with the normal bungeecord

**Comment by CzlowiekKuktas** [comment]
This problem doesn't exist on normal BungeeCord (for example 1119 build). When you switch to Waterfall/Travertine/HexaCord this problem appears right away. Host issue?
@i9hdkill Please re-open this issue.

**Comment by MJRLegends** [comment]
Ss i said i haven't tested it with that so i dont know if that works with me

**Comment by MJRLegends** [comment]
@CzlowiekKuktas does the normal bungeecord work with forge modded servers???

**Comment by CzlowiekKuktas** [comment]
I guess? I don't use it, I don't know.

**Comment by MJRLegends** [comment]
@CzlowiekKuktas well i just tried it and no one could join my modded servers not the hub which is spigot

**Comment by CzlowiekKuktas** [comment]
BungeeCord #1119 supports only 1.7 and 1.8.

**Comment by MJRLegends** [comment]
yeah im using 1.7.10 modded servers

**Comment by CzlowiekKuktas** [comment]
Why BungeeCord would not have support of Forge servers? :O

**Comment by MJRLegends** [comment]
@CzlowiekKuktas well the official bungeecord doesnt work thats why im asking also i dont like how your making me seem stupid....

**Comment by CzlowiekKuktas** [comment]
I don't know what you are talking about.

**Comment by MJRLegends** [comment]
I dont understand how this problem is happening as i havent changed anything with my server in weeks so why did it start happening a few days back and before??

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/c4adb600c13d4a5593fa03a106072917.png)

**Comment by CzlowiekKuktas** [comment]
I don't think HexaCord is the fault od your problem.

**Comment by MJRLegends** [comment]
yeah i know that but what is

**Comment by CzlowiekKuktas** [comment]
Well, THAT could be host issue or ddos, maybe broken plugins.

**Comment by MJRLegends** [comment]
Already check no dddos and the dedicated server have confirmed that and ive tired running bungeecord without plugins and nothing has changed plugin wise with all of my servers in weeks

**Comment by CzlowiekKuktas** [comment]
Maybe it's crasher.

**Comment by MJRLegends** [comment]
But what with and why only now and why is it at random times and not all the time

**Comment by CzlowiekKuktas** [comment]
With crasher you can do it anytime.

**Comment by MJRLegends** [comment]
What is it and how can i stop it

**Comment by MJRLegends** [comment]
Thats what i dont know haha

**Comment by CzlowiekKuktas** [comment]
The best way is using the latest version of the spigot.

**Comment by MJRLegends** [comment]
I use spigot on the hub server and thermos in the modded servers so if it was a issue why is it happening now not then

**Comment by CzlowiekKuktas** [comment]
Well, it's not really an issue about crashers or kicking player with 'Timed out'.

**Comment by MJRLegends** [comment]
Huh? Im not sure to what you mean

**Comment by CzlowiekKuktas** [comment]
CREATE NEW ISSUE, HERE I POSTED A PROBLEM WITH KICKING PLAYERS WITH PROXY ERROR.

**Comment by MJRLegends** [comment]
Fixed my issue :P

**Comment by ghacproductions** [comment]
@MJRLegends  You may want to provide some informations on how to fix the problem as this may also help others.
