### ISSUE TITLE
[Suggestion] Direct link to download latest version

### ISSUE THREAD

**Issue by KatsuroKurosaki** [HexagonMC/BungeeCord#89]
Cheers everybody!

I would like to ask if it will be possible to have a direct download link that always will point to latest version. Actually we have links like this:

https://github.com/HexagonMC/BungeeCord/releases/download/v98/BungeeCord.jar

And if someone wants to download latest version, it would be nice to have it in a link like:

https://github.com/HexagonMC/BungeeCord/releases/download/latest/BungeeCord.jar

Let me know if it will be possible to do this :D
Regards!

**Comment by KasperFranz** [comment]
that isn't possible with github as far as I know

**Comment by MJRLegends** [comment]
No its not possible

**Comment by KatsuroKurosaki** [comment]
Damn, that would be nice to have a latest jar link, in order to download it using a bash script and wget command.
Thank you anyway guys =] keep up the good work!
