### ISSUE TITLE
BungeeAdminTools

### ISSUE THREAD

**Issue by James137137** [HexagonMC/BungeeCord#9]
When installing BungeeAdminTools it would not enabled due to the plugin checking the build number (https://github.com/alphartdev/BungeeAdminTools/blob/master/src/main/java/fr/Alphart/BAT/BAT.java#L66) not sure if there's a simple work around for this, or whether it is an issue for HexagonMC/BungeeCord or not

**Comment by James137137** [comment]
how many people use BAT anyway? (our server does) If most people don't use BAT then we don't need to support it.

**Comment by James137137** [comment]
@alphartdev what would you suggest?

**Comment by Zartec** [comment]
The only thing i could do is to change the name of the server.

Then BAT would print a warning an continues.

**Comment by James137137** [comment]
yeah. either that if give the responsibility to the server Admins (I just did this: https://github.com/James137137/BungeeAdminTools/commit/0351905e03ce0bae9dc96256f8a36e94f3539fd3)

**Comment by PsychoLynx** [comment]
@James137137 Could I get a JAR of that? I'm hopeless with Github and could really use this update

**Comment by alphartdev** [comment]
Fixed since 1/2 days
https://github.com/alphartdev/BungeeAdminTools/pull/37

**Comment by alphartdev** [comment]
And PsychoLynx there is a link in the post I sent you.

**Comment by PsychoLynx** [comment]
@alphartdev I tried really hard to find the place download the jar, but I can't for the life of me find the download link anywhere on the Travis.ci build page. Maybe I'm just hopeless >.>" Sorry for my incompetence

**Comment by alphartdev** [comment]
My bad you're right it seems like the link has been removed since then. I'll build you a new one today.

**Comment by PsychoLynx** [comment]
Thanks man! Much appreciated :)

**Comment by ghacproductions** [comment]
@alphartdev @PsychoLynx I'm not sure if your changes will work as we didn't change the Proxy-name (is still "BungeeCord")

**Comment by PsychoLynx** [comment]
@ghacproductions I believe the version will add a config option to toggle the version check off entirely, though - so that shouldn't be a problem, I think?

**Comment by ghacproductions** [comment]
In the master branch, there is (this line)[https://github.com/alphartdev/BungeeAdminTools/blob/master/src/main/java/fr/Alphart/BAT/BAT.java#L62], as the name is still "BungeeCord", that sould trigger the version test.

**Comment by alphartdev** [comment]
Then I'll add something else to manually skip thé test

**Comment by ghacproductions** [comment]
@alphartdev That will be the best solution. I'll close this issue now as this is on the side of BungeeAdminTools.

**Comment by James137137** [comment]
@PsychoLynx: Sorry for the delay http://jenkins.lolnet.co.nz/view/Other/job/BungeeAdminTools/lastSuccessfulBuild/artifact/target/BungeeAdminTools-1.4.1.jar should do its just a build from https://github.com/James137137/BungeeAdminTools/tree/ignoreBuildCheck

**Comment by James137137** [comment]
anyway... as of 1.4.1 is should be fixed
