### ISSUE TITLE
Invalid UUID string

### ISSUE THREAD

**Issue by MrPowerGamerBR** [HexagonMC/BungeeCord#93]
```[21:18:49 INFO]: MrPowerGamerBR[/152.250.141.125:46415] logged in with entity id 10575 at ([world]5393.441801919033, 58.0625, 1022.0870465610416)
[21:18:49 INFO]: MrPowerGamerBR lost connection: Internal Exception: java.lang.IllegalArgumentException: Invalid UUID string: af942f8ea7ab35fb98005e8ab081d065
```

The lobby is running ProtocolSupport 1.10.2 and the 1.7.2 client connects without any issues to it, however my main server is running ProtocolSupport 1.8.8 and the 1.7.2 client fails to connect, however 1.7.10 is able to connect without any issues.

**Comment by i9hdkill** [comment]
That is probably a bug in Protocolsupport as 1.7.2 on 1.10. works. It will never get fixed.

**Comment by MrPowerGamerBR** [comment]
@i9hdkill then I will close this issue because probably it is a ProtocolSupport issue (and PS in 1.8 isn't supported by Shevchik anymore)
